# Order: key, PT, ES, FR, DE, IT, PL, RO, HU, CZ, JA, ZHCN, ZHTW
A("Ok, I will not show it again.", "Ok, não vou mostrar novamente.", "De acuerdo, no lo volveré a mostrar.", "D'accord, je ne l'afficherai plus.", "OK, ich zeige es nicht mehr an.", "Ok, non lo mostrerò più.", "OK, nie będę tego więcej pokazywać.", "Bine, nu îl voi mai afișa.", "Rendben, többé nem jelenítem meg.", "Dobře, už to nebudu zobrazovat.", "わかりました。今後は表示しません。", "好的，以后不再显示。", "好的，以後不再顯示。")
A("Open", "Abrir", "Abrir", "Ouvrir", "Öffnen", "Apri", "Otwórz", "Deschide", "Megnyitás", "Otevřít", "開く", "打开", "開啟")
A("Open File Location", "Abrir local do arquivo", "Abrir ubicación del archivo", "Ouvrir l'emplacement du fichier", "Dateispeicherort öffnen", "Apri percorso file", "Otwórz lokalizację pliku", "Deschide locația fișierului", "Fájl helyének megnyitása", "Otevřít umístění souboru", "ファイルの場所を開く", "打开文件所在位置", "開啟檔案位置")
A("Open and edit multi-gigabyte text files instantly - where other editors can't keep up. Exclusive features like Python macros, AI to extract/analyze files, and much more.",
  "Abra e edite arquivos de texto de vários gigabytes instantaneamente - onde outros editores não acompanham. Recursos exclusivos como macros Python, IA para extrair/analisar arquivos e muito mais.",
  "Abra y edite al instante archivos de texto de varios gigabytes, donde otros editores no pueden. Funciones exclusivas como macros de Python, IA para extraer/analizar archivos y mucho más.",
  "Ouvrez et modifiez instantanément des fichiers texte de plusieurs gigaoctets - là où les autres éditeurs n'y arrivent pas. Fonctions exclusives comme les macros Python, l'IA pour extraire/analyser les fichiers, et bien plus.",
  "Öffnen und bearbeiten Sie Textdateien mit mehreren Gigabyte sofort - wo andere Editoren nicht mithalten. Exklusive Funktionen wie Python-Makros, KI zum Extrahieren/Analysieren von Dateien und vieles mehr.",
  "Apri e modifica all'istante file di testo di più gigabyte - dove gli altri editor non riescono. Funzioni esclusive come macro Python, IA per estrarre/analizzare i file e molto altro.",
  "Otwieraj i edytuj natychmiast wielogigabajtowe pliki tekstowe - tam, gdzie inne edytory nie nadążają. Wyjątkowe funkcje, takie jak makra Python, AI do wyodrębniania/analizy plików i wiele więcej.",
  "Deschideți și editați instantaneu fișiere text de mai mulți gigaocteți - acolo unde alte editoare nu fac față. Funcții exclusive precum macrocomenzi Python, AI pentru extragerea/analiza fișierelor și multe altele.",
  "Többgigabájtos szövegfájlok azonnali megnyitása és szerkesztése - ahol más szerkesztők elakadnak. Egyedi funkciók, például Python makrók, MI a fájlok kinyeréséhez/elemzéséhez és még sok más.",
  "Otevírejte a upravujte vícegigabajtové textové soubory okamžitě - tam, kde ostatní editory nestačí. Exkluzivní funkce jako makra Python, AI pro extrakci/analýzu souborů a mnohem více.",
  "数ギガバイトのテキストファイルを瞬時に開いて編集 - 他のエディターでは追いつけない場面でも。Python マクロ、ファイルの抽出/分析のための AI など、独自の機能が満載です。",
  "即时打开和编辑数 GB 的文本文件——其他编辑器无法胜任时依然流畅。独有功能包括 Python 宏、用于提取/分析文件的 AI 等等。",
  "即時開啟和編輯數 GB 的文字檔——其他編輯器無法勝任時依然流暢。獨有功能包括 Python 巨集、用於擷取/分析檔案的 AI 等等。")
A("Output:", "Saída:", "Salida:", "Sortie :", "Ausgabe:", "Output:", "Wyjście:", "Ieșire:", "Kimenet:", "Výstup:", "出力:", "输出：", "輸出：")
A("Outputs true/false per line - ideal after CSV imports or conversions.",
  "Gera true/false por linha - ideal após importações ou conversões de CSV.", "Genera true/false por línea: ideal tras importaciones o conversiones de CSV.",
  "Produit true/false par ligne - idéal après des imports ou conversions CSV.", "Gibt pro Zeile true/false aus - ideal nach CSV-Importen oder Konvertierungen.",
  "Restituisce true/false per riga - ideale dopo importazioni o conversioni CSV.", "Zwraca true/false dla każdego wiersza - idealne po imporcie lub konwersji CSV.",
  "Returnează true/false pe linie - ideal după importuri sau conversii CSV.", "Soronként true/false értéket ad - ideális CSV-importálás vagy -átalakítás után.",
  "Vypíše true/false pro každý řádek - ideální po importu či převodu CSV.", "行ごとに true/false を出力します。CSV の取り込みや変換の後に最適です。",
  "每行输出 true/false——非常适合 CSV 导入或转换之后使用。", "每行輸出 true/false——非常適合 CSV 匯入或轉換之後使用。")
A("Paste clipboard lines into file at selected line", "Colar linhas da área de transferência no arquivo na linha selecionada", "Pegar líneas del portapapeles en el archivo en la línea seleccionada", "Coller les lignes du presse-papiers dans le fichier à la ligne sélectionnée", "Zeilen aus der Zwischenablage an der ausgewählten Zeile in die Datei einfügen", "Incolla le righe degli appunti nel file alla riga selezionata", "Wklej wiersze ze schowka do pliku w zaznaczonym wierszu", "Lipește liniile din clipboard în fișier la linia selectată", "Vágólap sorainak beillesztése a fájlba a kijelölt sornál", "Vložit řádky ze schránky do souboru na vybraný řádek", "クリップボードの行を選択行の位置でファイルに貼り付け", "将剪贴板中的行粘贴到文件的所选行处", "將剪貼簿中的行貼到檔案的所選行處")
A("Pattern/Regex\r\nCtrl+Alt+P", "Padrão/Regex\r\nCtrl+Alt+P", "Patrón/Regex\r\nCtrl+Alt+P", "Motif/Regex\r\nCtrl+Alt+P", "Muster/Regex\r\nCtrl+Alt+P", "Schema/Regex\r\nCtrl+Alt+P", "Wzorzec/Regex\r\nCtrl+Alt+P", "Șablon/Regex\r\nCtrl+Alt+P", "Minta/Regex\r\nCtrl+Alt+P", "Vzor/Regex\r\nCtrl+Alt+P", "パターン/正規表現\r\nCtrl+Alt+P", "模式/正则\r\nCtrl+Alt+P", "模式/正則\r\nCtrl+Alt+P")
A("Pattern/Regex is evaluated line-by-line. In Split mode: a new part starts when a line matches. In Regex modes: a single output file is produced. JS-style /pattern/gi syntax is accepted.",
  "O Padrão/Regex é avaliado linha a linha. No modo Dividir: uma nova parte começa quando uma linha corresponde. Nos modos Regex: é gerado um único arquivo de saída. A sintaxe /padrão/gi no estilo JS é aceita.",
  "El Patrón/Regex se evalúa línea por línea. En modo Dividir: una nueva parte comienza cuando una línea coincide. En los modos Regex: se genera un único archivo de salida. Se acepta la sintaxis /patrón/gi al estilo JS.",
  "Le motif/Regex est évalué ligne par ligne. En mode Découpage : une nouvelle partie commence quand une ligne correspond. En modes Regex : un seul fichier de sortie est produit. La syntaxe /motif/gi de style JS est acceptée.",
  "Muster/Regex wird zeilenweise ausgewertet. Im Aufteilungsmodus beginnt ein neuer Teil, wenn eine Zeile passt. In den Regex-Modi wird eine einzige Ausgabedatei erzeugt. JS-Syntax /muster/gi wird akzeptiert.",
  "Schema/Regex viene valutato riga per riga. In modalità Divisione: una nuova parte inizia quando una riga corrisponde. Nelle modalità Regex: viene prodotto un unico file di output. È accettata la sintassi /schema/gi in stile JS.",
  "Wzorzec/Regex jest oceniany wiersz po wierszu. W trybie Podziału: nowa część zaczyna się, gdy wiersz pasuje. W trybach Regex: powstaje jeden plik wyjściowy. Akceptowana jest składnia /wzorzec/gi w stylu JS.",
  "Șablonul/Regex este evaluat linie cu linie. În modul Împărțire: o parte nouă începe când o linie se potrivește. În modurile Regex: se produce un singur fișier de ieșire. Se acceptă sintaxa /șablon/gi în stil JS.",
  "A minta/regex kiértékelése soronként történik. Felosztás módban: új rész kezdődik, ha egy sor illeszkedik. Regex módokban: egyetlen kimeneti fájl készül. A JS-stílusú /minta/gi szintaxis is elfogadott.",
  "Vzor/Regex se vyhodnocuje řádek po řádku. V režimu Rozdělit: nová část začne, když řádek odpovídá. V režimech Regex: vznikne jediný výstupní soubor. Je přijímána syntaxe /vzor/gi ve stylu JS.",
  "パターン/正規表現は 1 行ずつ評価されます。分割モードでは、行が一致すると新しいパートが始まります。正規表現モードでは、出力ファイルは 1 つです。JS 形式の /pattern/gi 構文も使用できます。",
  "模式/正则按行逐一评估。拆分模式：行匹配时开始新的部分。正则模式：生成单个输出文件。支持 JS 风格的 /pattern/gi 语法。",
  "模式/正則逐行評估。分割模式：行相符時開始新的部分。正則模式：產生單一輸出檔案。支援 JS 風格的 /pattern/gi 語法。")
A("Pattern/Regex:", "Padrão/Regex:", "Patrón/Regex:", "Motif/Regex :", "Muster/Regex:", "Schema/Regex:", "Wzorzec/Regex:", "Șablon/Regex:", "Minta/Regex:", "Vzor/Regex:", "パターン/正規表現:", "模式/正则：", "模式/正則：")
A("Please enter a Python script in the editor.", "Digite um script Python no editor.", "Introduzca un script de Python en el editor.", "Veuillez saisir un script Python dans l'éditeur.", "Bitte geben Sie im Editor ein Python-Skript ein.", "Inserisci uno script Python nell'editor.", "Wprowadź skrypt Python w edytorze.", "Introduceți un script Python în editor.", "Írjon be egy Python szkriptet a szerkesztőbe.", "Zadejte do editoru skript Python.", "エディターに Python スクリプトを入力してください。", "请在编辑器中输入 Python 脚本。", "請在編輯器中輸入 Python 指令碼。")
A("Please enter a valid file list, one per line, example", "Informe uma lista de arquivos válida, um por linha, exemplo", "Introduzca una lista de archivos válida, uno por línea, ejemplo", "Veuillez saisir une liste de fichiers valide, un par ligne, exemple", "Bitte eine gültige Dateiliste eingeben, eine Datei pro Zeile, Beispiel", "Inserisci un elenco di file valido, uno per riga, esempio", "Wprowadź prawidłową listę plików, po jednym w wierszu, przykład", "Introduceți o listă validă de fișiere, câte unul pe linie, exemplu", "Adjon meg érvényes fájllistát, soronként egyet, például", "Zadejte platný seznam souborů, jeden na řádek, příklad", "有効なファイル一覧を 1 行に 1 つずつ入力してください。例", "请输入有效的文件列表，每行一个，例如", "請輸入有效的檔案清單，每行一個，例如")
A("Please select or check one or more lines first.", "Selecione ou marque uma ou mais linhas primeiro.", "Seleccione o marque una o más líneas primero.", "Veuillez d'abord sélectionner ou cocher une ou plusieurs lignes.", "Bitte zuerst eine oder mehrere Zeilen auswählen oder markieren.", "Seleziona o spunta prima una o più righe.", "Najpierw zaznacz lub zaznacz polem wyboru jeden lub więcej wierszy.", "Selectați sau bifați mai întâi una sau mai multe linii.", "Először jelöljön ki vagy pipáljon be egy vagy több sort.", "Nejprve vyberte nebo zaškrtněte jeden či více řádků.", "先に 1 行以上を選択またはチェックしてください。", "请先选择或勾选一行或多行。", "請先選取或勾選一行或多行。")
A("Portuguese (Brazil)", "Português (Brasil)", "Portugués (Brasil)", "Portugais (Brésil)", "Portugiesisch (Brasilien)", "Portoghese (Brasile)", "Portugalski (Brazylia)", "Portugheză (Brazilia)", "Portugál (Brazília)", "Portugalština (Brazílie)", "ポルトガル語（ブラジル）", "葡萄牙语（巴西）", "葡萄牙語（巴西）")
A("Preview summary (sampled): %d matching lines in first %d lines scanned.",
  "Resumo da pré-visualização (amostra): %d linhas correspondentes nas primeiras %d linhas analisadas.", "Resumen de vista previa (muestra): %d líneas coincidentes en las primeras %d líneas analizadas.",
  "Résumé de l'aperçu (échantillon) : %d lignes correspondantes dans les %d premières lignes analysées.", "Vorschau-Zusammenfassung (Stichprobe): %d passende Zeilen in den ersten %d geprüften Zeilen.",
  "Riepilogo anteprima (campione): %d righe corrispondenti nelle prime %d righe analizzate.", "Podsumowanie podglądu (próbka): %d pasujących wierszy w pierwszych %d przeskanowanych wierszach.",
  "Rezumat previzualizare (eșantion): %d linii potrivite în primele %d linii scanate.", "Előnézet összegzése (minta): %d illeszkedő sor az első %d vizsgált sorban.",
  "Souhrn náhledu (vzorek): %d odpovídajících řádků v prvních %d prohledaných řádcích.", "プレビューの概要（サンプル）: 最初の走査行のうち %d 行が一致（走査行数 %d）。",
  "预览摘要（抽样）：%d 个匹配行（共扫描前 %d 行）。", "預覽摘要（抽樣）：%d 個相符行（共掃描前 %d 行）。")
A("Preview summary: file is too large to auto-validate. Click Preview to sample matches (fast), or Confirm to run full processing.",
  "Resumo da pré-visualização: o arquivo é grande demais para validação automática. Clique em Pré-visualizar para amostrar correspondências (rápido) ou em Confirmar para executar o processamento completo.",
  "Resumen de vista previa: el archivo es demasiado grande para validarlo automáticamente. Haga clic en Vista previa para muestrear coincidencias (rápido) o en Confirmar para el procesamiento completo.",
  "Résumé de l'aperçu : le fichier est trop volumineux pour une validation automatique. Cliquez sur Aperçu pour échantillonner les correspondances (rapide), ou sur Confirmer pour lancer le traitement complet.",
  "Vorschau-Zusammenfassung: Die Datei ist zu groß für eine automatische Prüfung. Klicken Sie auf Vorschau für Stichproben (schnell) oder auf Bestätigen für die vollständige Verarbeitung.",
  "Riepilogo anteprima: il file è troppo grande per la convalida automatica. Fai clic su Anteprima per campionare le corrispondenze (veloce) o su Conferma per l'elaborazione completa.",
  "Podsumowanie podglądu: plik jest zbyt duży do automatycznej weryfikacji. Kliknij Podgląd, aby pobrać próbkę dopasowań (szybko), lub Potwierdź, aby uruchomić pełne przetwarzanie.",
  "Rezumat previzualizare: fișierul este prea mare pentru validare automată. Faceți clic pe Previzualizare pentru un eșantion de potriviri (rapid) sau pe Confirmare pentru procesarea completă.",
  "Előnézet összegzése: a fájl túl nagy az automatikus ellenőrzéshez. Kattintson az Előnézet gombra a találatok mintavételéhez (gyors), vagy a Megerősítés gombra a teljes feldolgozáshoz.",
  "Souhrn náhledu: soubor je příliš velký pro automatické ověření. Klikněte na Náhled pro vzorek shod (rychlé), nebo na Potvrdit pro úplné zpracování.",
  "プレビューの概要: ファイルが大きすぎるため自動検証できません。[プレビュー] で一致をサンプリング（高速）するか、[確認] で全体の処理を実行してください。",
  "预览摘要：文件太大，无法自动验证。单击“预览”抽样匹配（快速），或单击“确认”执行完整处理。",
  "預覽摘要：檔案太大，無法自動驗證。按一下「預覽」抽樣相符項（快速），或按一下「確認」執行完整處理。")
A("Prices: ", "Preços: ", "Precios: ", "Tarifs : ", "Preise: ", "Prezzi: ", "Ceny: ", "Prețuri: ", "Árak: ", "Ceny: ", "価格: ", "价格：", "價格：")
A("Processing ...", "Processando ...", "Procesando ...", "Traitement ...", "Verarbeitung ...", "Elaborazione ...", "Przetwarzanie ...", "Se procesează ...", "Feldolgozás ...", "Zpracování ...", "処理中 ...", "正在处理 ...", "正在處理 ...")
A("Processing diff...", "Processando diferenças...", "Procesando diferencias...", "Traitement des différences...", "Unterschiede werden verarbeitet...", "Elaborazione differenze...", "Przetwarzanie różnic...", "Se procesează diferențele...", "Eltérések feldolgozása...", "Zpracování rozdílů...", "差分を処理中...", "正在处理差异...", "正在處理差異...")
A("Protection Activated (FastFile)", "Proteção ativada (FastFile)", "Protección activada (FastFile)", "Protection activée (FastFile)", "Schutz aktiviert (FastFile)", "Protezione attivata (FastFile)", "Ochrona aktywowana (FastFile)", "Protecție activată (FastFile)", "Védelem aktiválva (FastFile)", "Ochrana aktivována (FastFile)", "保護が作動しました (FastFile)", "保护已启动 (FastFile)", "保護已啟動 (FastFile)")
A("Python Macro Integration", "Integração de macros Python", "Integración de macros de Python", "Intégration des macros Python", "Python-Makro-Integration", "Integrazione macro Python", "Integracja makr Python", "Integrare macrocomenzi Python", "Python makró integráció", "Integrace maker Python", "Python マクロ統合", "Python 宏集成", "Python 巨集整合")
A("Random Skin", "Skin aleatória", "Skin aleatoria", "Skin aléatoire", "Zufälliger Skin", "Skin casuale", "Losowa skórka", "Skin aleatoriu", "Véletlen skin", "Náhodný skin", "ランダムスキン", "随机皮肤", "隨機外觀")
A("Read\r\nCtrl+1", "Ler\r\nCtrl+1", "Leer\r\nCtrl+1", "Lire\r\nCtrl+1", "Lesen\r\nCtrl+1", "Leggi\r\nCtrl+1", "Czytaj\r\nCtrl+1", "Citire\r\nCtrl+1", "Olvasás\r\nCtrl+1", "Číst\r\nCtrl+1", "読み込み\r\nCtrl+1", "读取\r\nCtrl+1", "讀取\r\nCtrl+1")
A("Read\r\nF5", "Ler\r\nF5", "Leer\r\nF5", "Lire\r\nF5", "Lesen\r\nF5", "Leggi\r\nF5", "Czytaj\r\nF5", "Citire\r\nF5", "Olvasás\r\nF5", "Číst\r\nF5", "読み込み\r\nF5", "读取\r\nF5", "讀取\r\nF5")
A("Read / Load (F5)", "Ler / Carregar (F5)", "Leer / Cargar (F5)", "Lire / Charger (F5)", "Lesen / Laden (F5)", "Leggi / Carica (F5)", "Czytaj / Wczytaj (F5)", "Citire / Încărcare (F5)", "Olvasás / Betöltés (F5)", "Číst / Načíst (F5)", "読み込み / ロード (F5)", "读取 / 加载 (F5)", "讀取 / 載入 (F5)")
A("Read-only session is enabled. Turn it off to modify the file.", "A sessão somente leitura está ativada. Desative-a para modificar o arquivo.", "La sesión de solo lectura está activada. Desactívela para modificar el archivo.", "La session en lecture seule est activée. Désactivez-la pour modifier le fichier.", "Die Nur-Lese-Sitzung ist aktiviert. Deaktivieren Sie sie, um die Datei zu ändern.", "La sessione di sola lettura è attiva. Disattivala per modificare il file.", "Sesja tylko do odczytu jest włączona. Wyłącz ją, aby zmodyfikować plik.", "Sesiunea doar citire este activă. Dezactivați-o pentru a modifica fișierul.", "Csak olvasható munkamenet van bekapcsolva. Kapcsolja ki a fájl módosításához.", "Je zapnuta relace jen pro čtení. Pro úpravu souboru ji vypněte.", "読み取り専用セッションが有効です。ファイルを変更するには無効にしてください。", "只读会话已启用。请关闭后再修改文件。", "唯讀工作階段已啟用。請關閉後再修改檔案。")
A("Recent", "Recentes", "Recientes", "Récents", "Zuletzt verwendet", "Recenti", "Ostatnie", "Recente", "Legutóbbi", "Nedávné", "最近使ったファイル", "最近", "最近")
A("Redo: paste %d line(s) at line %d", "Refazer: colar %d linha(s) na linha %d", "Rehacer: pegar %d línea(s) en la línea %d", "Rétablir : coller %d ligne(s) à la ligne %d", "Wiederholen: %d Zeile(n) ab Zeile %d einfügen", "Ripeti: incolla %d riga/e alla riga %d", "Ponów: wklej %d wiersz(y) od wiersza %d", "Refacere: lipire %d linie/linii la linia %d", "Újra: %d sor beillesztése a(z) %d. sornál", "Znovu: vložit %d řádek na řádek %d", "やり直し: %d 行を貼り付け（行 %d）", "重做：粘贴 %d 行（第 %d 行）", "取消復原：貼上 %d 行（第 %d 行）")
A("Regex %s completed. %d line(s) processed in %s.\r\nOutput: %s",
  "Regex %s concluído. %d linha(s) processada(s) em %s.\r\nSaída: %s", "Regex %s completado. %d línea(s) procesada(s) en %s.\r\nSalida: %s",
  "Regex %s terminé. %d ligne(s) traitée(s) en %s.\r\nSortie : %s", "Regex %s abgeschlossen. %d Zeile(n) in %s verarbeitet.\r\nAusgabe: %s",
  "Regex %s completato. %d riga/e elaborata/e in %s.\r\nOutput: %s", "Regex %s zakończony. Przetworzono %d wiersz(y) w %s.\r\nWyjście: %s",
  "Regex %s finalizat. %d linie/linii procesate în %s.\r\nIeșire: %s", "Regex %s kész. %d sor feldolgozva, idő: %s.\r\nKimenet: %s",
  "Regex %s dokončen. Zpracováno %d řádků za %s.\r\nVýstup: %s", "正規表現 %s が完了しました。%d 行を処理（所要時間 %s）。\r\n出力: %s",
  "正则 %s 已完成。已处理 %d 行，用时 %s。\r\n输出：%s", "正則 %s 已完成。已處理 %d 行，耗時 %s。\r\n輸出：%s")
A("Regex %s completed. %d line(s) processed in %s. Output: %s",
  "Regex %s concluído. %d linha(s) processada(s) em %s. Saída: %s", "Regex %s completado. %d línea(s) procesada(s) en %s. Salida: %s",
  "Regex %s terminé. %d ligne(s) traitée(s) en %s. Sortie : %s", "Regex %s abgeschlossen. %d Zeile(n) in %s verarbeitet. Ausgabe: %s",
  "Regex %s completato. %d riga/e elaborata/e in %s. Output: %s", "Regex %s zakończony. Przetworzono %d wiersz(y) w %s. Wyjście: %s",
  "Regex %s finalizat. %d linie/linii procesate în %s. Ieșire: %s", "Regex %s kész. %d sor feldolgozva, idő: %s. Kimenet: %s",
  "Regex %s dokončen. Zpracováno %d řádků za %s. Výstup: %s", "正規表現 %s が完了しました。%d 行を処理（所要時間 %s）。出力: %s",
  "正则 %s 已完成。已处理 %d 行，用时 %s。输出：%s", "正則 %s 已完成。已處理 %d 行，耗時 %s。輸出：%s")
A("Regex Test: Write \"true\"/\"false\"", "Teste Regex: gravar \"true\"/\"false\"", "Prueba Regex: escribir \"true\"/\"false\"", "Test Regex : écrire « true »/« false »", "Regex-Test: \"true\"/\"false\" schreiben", "Test Regex: scrivi \"true\"/\"false\"", "Test Regex: zapisz \"true\"/\"false\"", "Test Regex: scrie \"true\"/\"false\"", "Regex teszt: \"true\"/\"false\" írása", "Test Regex: zapsat \"true\"/\"false\"", "正規表現テスト: \"true\"/\"false\" を書き込む", "正则测试：写入 \"true\"/\"false\"", "正則測試：寫入 \"true\"/\"false\"")
A("Regex filter - keep only lines where regex matches         (like JS filter)",
  "Filtro Regex - manter apenas as linhas em que o regex corresponde   (como filter do JS)", "Filtro Regex - conservar solo las líneas en las que coincide el regex   (como filter de JS)",
  "Filtre Regex - ne garder que les lignes où la regex correspond   (comme filter en JS)", "Regex-Filter - nur Zeilen behalten, in denen die Regex passt   (wie JS filter)",
  "Filtro Regex - mantieni solo le righe in cui la regex corrisponde   (come filter di JS)", "Filtr Regex - zachowaj tylko wiersze pasujące do regex   (jak filter w JS)",
  "Filtru Regex - păstrează doar liniile potrivite cu regex   (ca filter din JS)", "Regex szűrő - csak az illeszkedő sorok megtartása   (mint a JS filter)",
  "Filtr Regex - ponechat jen řádky odpovídající regexu   (jako JS filter)", "正規表現フィルター - 一致する行のみ残す   (JS の filter と同様)",
  "正则过滤 - 仅保留正则匹配的行   (类似 JS filter)", "正則篩選 - 僅保留正則相符的行   (類似 JS filter)")
A("Regex filter requires a line index. Choose YES to index first, or use plain text.",
  "O filtro Regex requer um índice de linhas. Escolha SIM para indexar primeiro ou use texto simples.", "El filtro Regex requiere un índice de líneas. Elija SÍ para indexar primero o use texto simple.",
  "Le filtre Regex nécessite un index des lignes. Choisissez OUI pour indexer d'abord, ou utilisez du texte brut.", "Der Regex-Filter benötigt einen Zeilenindex. Wählen Sie JA, um zuerst zu indizieren, oder verwenden Sie reinen Text.",
  "Il filtro Regex richiede un indice delle righe. Scegli SÌ per indicizzare prima, oppure usa testo semplice.", "Filtr Regex wymaga indeksu wierszy. Wybierz TAK, aby najpierw zindeksować, lub użyj zwykłego tekstu.",
  "Filtrul Regex necesită un index de linii. Alegeți DA pentru a indexa mai întâi sau folosiți text simplu.", "A regex szűrőhöz sorindex kell. Válassza az IGEN lehetőséget az indexeléshez, vagy használjon egyszerű szöveget.",
  "Filtr Regex vyžaduje index řádků. Zvolte ANO pro předchozí indexaci, nebo použijte prostý text.", "正規表現フィルターには行インデックスが必要です。先にインデックスを作成するには [はい] を選ぶか、プレーンテキストを使用してください。",
  "正则过滤需要行索引。选择“是”先建立索引，或使用纯文本。", "正則篩選需要行索引。選擇「是」先建立索引，或使用純文字。")
A("Regex match - extract all occurrences from each line  (like JS match)",
  "Regex match - extrair todas as ocorrências de cada linha  (como match do JS)", "Regex match - extraer todas las coincidencias de cada línea  (como match de JS)",
  "Regex match - extraire toutes les occurrences de chaque ligne  (comme match en JS)", "Regex-Match - alle Vorkommen aus jeder Zeile extrahieren  (wie JS match)",
  "Regex match - estrai tutte le occorrenze da ogni riga  (come match di JS)", "Regex match - wyodrębnij wszystkie wystąpienia z każdego wiersza  (jak match w JS)",
  "Regex match - extrage toate aparițiile din fiecare linie  (ca match din JS)", "Regex match - minden előfordulás kinyerése soronként  (mint a JS match)",
  "Regex match - extrahovat všechny výskyty z každého řádku  (jako JS match)", "正規表現マッチ - 各行からすべての一致を抽出  (JS の match と同様)",
  "正则匹配 - 从每行提取所有匹配项  (类似 JS match)", "正則比對 - 從每行擷取所有相符項  (類似 JS match)")
A("Regex replace - replace matches in every line              (like JS replace)",
  "Regex replace - substituir correspondências em cada linha   (como replace do JS)", "Regex replace - reemplazar coincidencias en cada línea   (como replace de JS)",
  "Regex replace - remplacer les correspondances dans chaque ligne   (comme replace en JS)", "Regex-Replace - Treffer in jeder Zeile ersetzen   (wie JS replace)",
  "Regex replace - sostituisci le corrispondenze in ogni riga   (come replace di JS)", "Regex replace - zamień dopasowania w każdym wierszu   (jak replace w JS)",
  "Regex replace - înlocuiește potrivirile în fiecare linie   (ca replace din JS)", "Regex replace - találatok cseréje minden sorban   (mint a JS replace)",
  "Regex replace - nahradit shody v každém řádku   (jako JS replace)", "正規表現置換 - 各行の一致を置換   (JS の replace と同様)",
  "正则替换 - 替换每行中的匹配项   (类似 JS replace)", "正則取代 - 取代每行中的相符項   (類似 JS replace)")
A("Regex test - write \"true\"/\"false\" for every line        (like JS test)",
  "Regex test - gravar \"true\"/\"false\" para cada linha   (como test do JS)", "Regex test - escribir \"true\"/\"false\" para cada línea   (como test de JS)",
  "Regex test - écrire « true »/« false » pour chaque ligne   (comme test en JS)", "Regex-Test - für jede Zeile \"true\"/\"false\" schreiben   (wie JS test)",
  "Regex test - scrivi \"true\"/\"false\" per ogni riga   (come test di JS)", "Regex test - zapisz \"true\"/\"false\" dla każdego wiersza   (jak test w JS)",
  "Regex test - scrie \"true\"/\"false\" pentru fiecare linie   (ca test din JS)", "Regex teszt - \"true\"/\"false\" írása minden sorhoz   (mint a JS test)",
  "Regex test - zapsat \"true\"/\"false\" pro každý řádek   (jako JS test)", "正規表現テスト - 各行に \"true\"/\"false\" を書き込む   (JS の test と同様)",
  "正则测试 - 为每行写入 \"true\"/\"false\"   (类似 JS test)", "正則測試 - 為每行寫入 \"true\"/\"false\"   (類似 JS test)")
A("Remove selected file from recent list?", "Remover o arquivo selecionado da lista de recentes?", "¿Quitar el archivo seleccionado de la lista de recientes?", "Retirer le fichier sélectionné de la liste des récents ?", "Ausgewählte Datei aus der Liste der zuletzt verwendeten entfernen?", "Rimuovere il file selezionato dall'elenco dei recenti?", "Usunąć wybrany plik z listy ostatnich?", "Eliminați fișierul selectat din lista celor recente?", "Eltávolítja a kijelölt fájlt a legutóbbiak listájából?", "Odebrat vybraný soubor ze seznamu nedávných?", "選択したファイルを最近使ったファイルの一覧から削除しますか?", "要从最近列表中移除所选文件吗？", "要從最近清單中移除所選檔案嗎？")
A("Removes trailing -2 / -3 style duplicates while keeping the canonical slug.",
  "Remove duplicatas finais no estilo -2 / -3 mantendo o slug canônico.", "Elimina duplicados finales del tipo -2 / -3 manteniendo el slug canónico.",
  "Supprime les doublons finaux de type -2 / -3 en conservant le slug canonique.", "Entfernt angehängte Duplikate im Stil -2 / -3 und behält den kanonischen Slug.",
  "Rimuove i duplicati finali in stile -2 / -3 mantenendo lo slug canonico.", "Usuwa końcowe duplikaty w stylu -2 / -3, zachowując kanoniczny slug.",
  "Elimină duplicatele finale de tip -2 / -3 păstrând slug-ul canonic.", "Eltávolítja a -2 / -3 stílusú záró duplikátumokat, a kanonikus slugot megtartva.",
  "Odstraní koncové duplikáty ve stylu -2 / -3 a zachová kanonický slug.", "正規のスラッグを保ったまま、末尾の -2 / -3 形式の重複を削除します。",
  "删除末尾 -2 / -3 样式的重复项，同时保留规范 slug。", "刪除結尾 -2 / -3 樣式的重複項，同時保留標準 slug。")
A("Replace All completed. %d replacement(s). Time: %s ms.", "Substituir tudo concluído. %d substituição(ões). Tempo: %s ms.", "Reemplazar todo completado. %d reemplazo(s). Tiempo: %s ms.", "Tout remplacer terminé. %d remplacement(s). Durée : %s ms.", "Alle ersetzen abgeschlossen. %d Ersetzung(en). Zeit: %s ms.", "Sostituisci tutto completato. %d sostituzione/i. Tempo: %s ms.", "Zamień wszystko zakończone. Zamian: %d. Czas: %s ms.", "Înlocuire totală finalizată. %d înlocuire/înlocuiri. Timp: %s ms.", "Összes cseréje kész. %d csere. Idő: %s ms.", "Nahradit vše dokončeno. Počet náhrad: %d. Čas: %s ms.", "すべて置換が完了しました。%d 件を置換。時間: %s ミリ秒。", "全部替换已完成。%d 处替换。用时：%s 毫秒。", "全部取代已完成。%d 處取代。耗時：%s 毫秒。")
A("Replace runs on each line; $1..$4 refer to the captured groups from left to right.",
  "A substituição é executada em cada linha; $1..$4 referem-se aos grupos capturados da esquerda para a direita.", "El reemplazo se ejecuta en cada línea; $1..$4 hacen referencia a los grupos capturados de izquierda a derecha.",
  "Le remplacement s'exécute sur chaque ligne ; $1..$4 désignent les groupes capturés de gauche à droite.", "Das Ersetzen läuft auf jeder Zeile; $1..$4 verweisen auf die erfassten Gruppen von links nach rechts.",
  "La sostituzione viene eseguita su ogni riga; $1..$4 indicano i gruppi catturati da sinistra a destra.", "Zamiana działa w każdym wierszu; $1..$4 odnoszą się do przechwyconych grup od lewej do prawej.",
  "Înlocuirea rulează pe fiecare linie; $1..$4 se referă la grupurile capturate de la stânga la dreapta.", "A csere minden soron lefut; a $1..$4 a rögzített csoportokra hivatkozik balról jobbra.",
  "Nahrazení probíhá na každém řádku; $1..$4 odkazují na zachycené skupiny zleva doprava.", "置換は各行で実行されます。$1..$4 は左から順にキャプチャグループを参照します。",
  "替换在每一行上运行；$1..$4 按从左到右的顺序引用捕获组。", "取代在每一行上執行；$1..$4 依從左到右的順序參照擷取群組。")
A("Replace substitutes only capture group 2 while keeping the honorific in group 1.",
  "A substituição troca apenas o grupo de captura 2, mantendo o título no grupo 1.", "El reemplazo sustituye solo el grupo de captura 2 y mantiene el tratamiento en el grupo 1.",
  "Le remplacement ne substitue que le groupe de capture 2 en conservant le titre dans le groupe 1.", "Das Ersetzen tauscht nur Erfassungsgruppe 2 aus und behält die Anrede in Gruppe 1.",
  "La sostituzione cambia solo il gruppo di cattura 2 mantenendo il titolo nel gruppo 1.", "Zamiana podmienia tylko grupę 2, zachowując tytuł w grupie 1.",
  "Înlocuirea schimbă doar grupul de captură 2, păstrând titlul în grupul 1.", "A csere csak a 2. rögzítési csoportot cseréli, a megszólítást az 1. csoportban hagyja.",
  "Nahrazení mění jen zachycenou skupinu 2 a titul ve skupině 1 zachová.", "置換ではキャプチャグループ 2 のみを置き換え、グループ 1 の敬称は保持します。",
  "替换仅替换捕获组 2，并保留组 1 中的称谓。", "取代僅取代擷取群組 2，並保留群組 1 中的稱謂。")
A("Replacement text (used by \"Regex replace\" mode only):", "Texto de substituição (usado apenas no modo \"Regex replace\"):", "Texto de reemplazo (solo para el modo \"Regex replace\"):", "Texte de remplacement (utilisé uniquement en mode « Regex replace ») :", "Ersetzungstext (nur im Modus \"Regex replace\"):", "Testo di sostituzione (usato solo in modalità \"Regex replace\"):", "Tekst zastępczy (używany tylko w trybie \"Regex replace\"):", "Text de înlocuire (folosit doar în modul \"Regex replace\"):", "Csereszöveg (csak \"Regex replace\" módban):", "Náhradní text (používá se jen v režimu \"Regex replace\"):", "置換テキスト（\"Regex replace\" モードのみ）:", "替换文本（仅用于“Regex replace”模式）：", "取代文字（僅用於「Regex replace」模式）：")
A("Run", "Executar", "Ejecutar", "Exécuter", "Ausführen", "Esegui", "Uruchom", "Rulează", "Futtatás", "Spustit", "実行", "运行", "執行")
A("Run error", "Erro de execução", "Error de ejecución", "Erreur d'exécution", "Ausführungsfehler", "Errore di esecuzione", "Błąd wykonania", "Eroare de execuție", "Futtatási hiba", "Chyba běhu", "実行エラー", "运行错误", "執行錯誤")
A("Run script", "Executar script", "Ejecutar script", "Exécuter le script", "Skript ausführen", "Esegui script", "Uruchom skrypt", "Rulează scriptul", "Szkript futtatása", "Spustit skript", "スクリプトを実行", "运行脚本", "執行指令碼")
A("Same 8-digit trailer on all scanned lines - this pattern matches every line or none; narrow using column-specific substring tests if needed.",
  "Mesmo sufixo de 8 dígitos em todas as linhas analisadas - este padrão corresponde a todas as linhas ou a nenhuma; restrinja com testes de substring específicos da coluna se necessário.",
  "Mismo sufijo de 8 dígitos en todas las líneas analizadas: este patrón coincide con todas las líneas o con ninguna; acótelo con pruebas de subcadena de columna si es necesario.",
  "Même suffixe de 8 chiffres sur toutes les lignes analysées - ce motif correspond à toutes les lignes ou à aucune ; restreignez-le avec des tests de sous-chaîne par colonne si nécessaire.",
  "Gleiche 8-stellige Endung in allen geprüften Zeilen - dieses Muster trifft jede oder keine Zeile; bei Bedarf mit spaltenspezifischen Teilstring-Tests eingrenzen.",
  "Stesso suffisso di 8 cifre su tutte le righe analizzate - questo schema corrisponde a tutte le righe o a nessuna; se necessario restringi con test di sottostringa per colonna.",
  "Ta sama 8-cyfrowa końcówka we wszystkich przeskanowanych wierszach - ten wzorzec pasuje do wszystkich wierszy albo do żadnego; w razie potrzeby zawęź testami podciągów w kolumnie.",
  "Același sufix de 8 cifre pe toate liniile scanate - acest șablon se potrivește tuturor liniilor sau niciuneia; restrângeți cu teste de subșir pe coloană dacă e nevoie.",
  "Minden vizsgált sorban azonos a 8 jegyű záró rész - ez a minta minden sorra vagy egyikre sem illeszkedik; szükség esetén szűkítse oszlopspecifikus részsztring-tesztekkel.",
  "Stejná 8místná koncovka na všech prohledaných řádcích - tento vzor odpovídá všem řádkům nebo žádnému; v případě potřeby jej zužte testy podřetězců ve sloupci.",
  "走査したすべての行で同じ 8 桁の末尾です。このパターンはすべての行に一致するか、どれにも一致しません。必要に応じて列固有の部分文字列テストで絞り込んでください。",
  "所有扫描行的 8 位结尾都相同——此模式要么匹配所有行，要么都不匹配；如有需要，请使用特定列的子串测试进行收窄。",
  "所有掃描行的 8 位結尾都相同——此模式要麼比對所有行，要麼都不比對；如有需要，請使用特定欄位的子字串測試加以縮小。")
A("Sample lines (raw, from current file):", "Linhas de amostra (brutas, do arquivo atual):", "Líneas de muestra (sin procesar, del archivo actual):", "Lignes d'exemple (brutes, du fichier actuel) :", "Beispielzeilen (roh, aus der aktuellen Datei):", "Righe di esempio (grezze, dal file corrente):", "Wiersze przykładowe (surowe, z bieżącego pliku):", "Linii de exemplu (brute, din fișierul curent):", "Mintasorok (nyers, az aktuális fájlból):", "Ukázkové řádky (nezpracované, z aktuálního souboru):", "サンプル行（現在のファイルからそのまま）:", "样本行（原始，来自当前文件）：", "樣本行（原始，來自目前檔案）：")
A("Sample lines from file (dynamic — changes when you pick another file):", "Linhas de amostra do arquivo (dinâmicas — mudam quando você escolhe outro arquivo):", "Líneas de muestra del archivo (dinámicas — cambian al elegir otro archivo):", "Lignes d'exemple du fichier (dynamiques — changent si vous choisissez un autre fichier) :", "Beispielzeilen aus der Datei (dynamisch — ändern sich bei Auswahl einer anderen Datei):", "Righe di esempio dal file (dinamiche — cambiano se scegli un altro file):", "Wiersze przykładowe z pliku (dynamiczne — zmieniają się po wybraniu innego pliku):", "Linii de exemplu din fișier (dinamice — se schimbă când alegeți alt fișier):", "Mintasorok a fájlból (dinamikus — más fájl választásakor változik):", "Ukázkové řádky ze souboru (dynamické — změní se při výběru jiného souboru):", "ファイルのサンプル行（動的 — 別のファイルを選ぶと変わります）:", "文件中的样本行（动态——选择其他文件时会变化）：", "檔案中的樣本行（動態——選擇其他檔案時會變化）：")
A("Sample tokens inferred from your columns - primary (region-like): \"%s\". Alternate token useful when categories drive file boundaries: \"%s\". Sort by the active key before splitting so each part stays coherent.",
  "Tokens de amostra inferidos das suas colunas - principal (tipo região): \"%s\". Token alternativo útil quando categorias definem os limites dos arquivos: \"%s\". Ordene pela chave ativa antes de dividir para que cada parte fique coerente.",
  "Tokens de muestra deducidos de sus columnas - principal (tipo región): \"%s\". Token alternativo útil cuando las categorías definen los límites de archivo: \"%s\". Ordene por la clave activa antes de dividir para que cada parte sea coherente.",
  "Jetons d'exemple déduits de vos colonnes - principal (type région) : « %s ». Jeton alternatif utile quand des catégories définissent les limites de fichiers : « %s ». Triez par la clé active avant de découper pour que chaque partie reste cohérente.",
  "Aus Ihren Spalten abgeleitete Beispiel-Tokens - primär (regionsartig): \"%s\". Alternatives Token, nützlich wenn Kategorien die Dateigrenzen bestimmen: \"%s\". Sortieren Sie vor dem Aufteilen nach dem aktiven Schlüssel, damit jeder Teil zusammenhängend bleibt.",
  "Token di esempio dedotti dalle tue colonne - principale (tipo regione): \"%s\". Token alternativo utile quando le categorie definiscono i confini dei file: \"%s\". Ordina per la chiave attiva prima di dividere, così ogni parte resta coerente.",
  "Przykładowe tokeny wywnioskowane z kolumn - główny (typu region): \"%s\". Alternatywny token przydatny, gdy kategorie wyznaczają granice plików: \"%s\". Przed podziałem posortuj według aktywnego klucza, aby każda część była spójna.",
  "Tokenuri de exemplu deduse din coloane - principal (de tip regiune): \"%s\". Token alternativ util când categoriile definesc limitele fișierelor: \"%s\". Sortați după cheia activă înainte de împărțire, ca fiecare parte să fie coerentă.",
  "Az oszlopokból kikövetkeztetett minta tokenek - elsődleges (régió jellegű): \"%s\". Alternatív token, ha kategóriák határozzák meg a fájlhatárokat: \"%s\". Felosztás előtt rendezzen az aktív kulcs szerint, hogy minden rész egységes maradjon.",
  "Ukázkové tokeny odvozené z vašich sloupců - primární (typu region): \"%s\". Alternativní token užitečný, když kategorie určují hranice souborů: \"%s\". Před rozdělením seřaďte podle aktivního klíče, aby každá část zůstala soudržná.",
  "列から推定したサンプルトークン - 主（地域のようなもの）: \"%s\"。カテゴリでファイル境界を決める場合に便利な代替トークン: \"%s\"。各パートの一貫性を保つため、分割前にアクティブなキーで並べ替えてください。",
  "从您的列推断出的样本标记——主要（类似区域）：\"%s\"。当类别决定文件边界时可用的备选标记：\"%s\"。拆分前请按当前键排序，使每个部分保持连贯。",
  "從您的欄位推斷出的樣本標記——主要（類似區域）：\"%s\"。當類別決定檔案邊界時可用的替代標記：\"%s\"。分割前請依目前鍵值排序，使每個部分保持連貫。")
A("Save file", "Salvar arquivo", "Guardar archivo", "Enregistrer le fichier", "Datei speichern", "Salva file", "Zapisz plik", "Salvează fișierul", "Fájl mentése", "Uložit soubor", "ファイルを保存", "保存文件", "儲存檔案")
A("Save output...", "Salvar saída...", "Guardar salida...", "Enregistrer la sortie...", "Ausgabe speichern...", "Salva output...", "Zapisz wyjście...", "Salvează ieșirea...", "Kimenet mentése...", "Uložit výstup...", "出力を保存...", "保存输出...", "儲存輸出...")
A("Script (define transform(line, ctx) -> str | None):", "Script (defina transform(line, ctx) -> str | None):", "Script (defina transform(line, ctx) -> str | None):", "Script (définissez transform(line, ctx) -> str | None) :", "Skript (transform(line, ctx) -> str | None definieren):", "Script (definisci transform(line, ctx) -> str | None):", "Skrypt (zdefiniuj transform(line, ctx) -> str | None):", "Script (definiți transform(line, ctx) -> str | None):", "Szkript (definiálja: transform(line, ctx) -> str | None):", "Skript (definujte transform(line, ctx) -> str | None):", "スクリプト（transform(line, ctx) -> str | None を定義）:", "脚本（定义 transform(line, ctx) -> str | None）：", "指令碼（定義 transform(line, ctx) -> str | None）：")
A("Script engine is not running.", "O mecanismo de script não está em execução.", "El motor de scripts no está en ejecución.", "Le moteur de script n'est pas en cours d'exécution.", "Die Skript-Engine läuft nicht.", "Il motore di script non è in esecuzione.", "Silnik skryptów nie jest uruchomiony.", "Motorul de script nu rulează.", "A szkriptmotor nem fut.", "Skriptovací engine neběží.", "スクリプトエンジンが実行されていません。", "脚本引擎未运行。", "指令碼引擎未執行。")
A("Search / index", "Pesquisar / indexar", "Buscar / indexar", "Rechercher / indexer", "Suchen / indizieren", "Cerca / indicizza", "Szukaj / indeksuj", "Căutare / indexare", "Keresés / indexelés", "Hledat / indexovat", "検索 / インデックス", "搜索 / 索引", "搜尋 / 索引")
A("Search error", "Erro de pesquisa", "Error de búsqueda", "Erreur de recherche", "Suchfehler", "Errore di ricerca", "Błąd wyszukiwania", "Eroare de căutare", "Keresési hiba", "Chyba hledání", "検索エラー", "搜索错误", "搜尋錯誤")
A("Search error: ", "Erro de pesquisa: ", "Error de búsqueda: ", "Erreur de recherche : ", "Suchfehler: ", "Errore di ricerca: ", "Błąd wyszukiwania: ", "Eroare de căutare: ", "Keresési hiba: ", "Chyba hledání: ", "検索エラー: ", "搜索错误：", "搜尋錯誤：")
A("Secondary pattern (same mode): Regex: ^.*,%s,.*$", "Padrão secundário (mesmo modo): Regex: ^.*,%s,.*$", "Patrón secundario (mismo modo): Regex: ^.*,%s,.*$", "Motif secondaire (même mode) : Regex: ^.*,%s,.*$", "Sekundäres Muster (gleicher Modus): Regex: ^.*,%s,.*$", "Schema secondario (stessa modalità): Regex: ^.*,%s,.*$", "Wzorzec dodatkowy (ten sam tryb): Regex: ^.*,%s,.*$", "Șablon secundar (același mod): Regex: ^.*,%s,.*$", "Másodlagos minta (azonos mód): Regex: ^.*,%s,.*$", "Sekundární vzor (stejný režim): Regex: ^.*,%s,.*$", "副パターン（同じモード）: Regex: ^.*,%s,.*$", "次要模式（相同模式）：Regex: ^.*,%s,.*$", "次要模式（相同模式）：Regex: ^.*,%s,.*$")
A("Segmented ops: &automatic (recommended)", "Operações segmentadas: &automático (recomendado)", "Operaciones segmentadas: &automático (recomendado)", "Opérations segmentées : &automatique (recommandé)", "Segmentierte Vorgänge: &automatisch (empfohlen)", "Operazioni segmentate: &automatico (consigliato)", "Operacje segmentowe: &automatycznie (zalecane)", "Operații segmentate: &automat (recomandat)", "Szegmentált műveletek: &automatikus (ajánlott)", "Segmentované operace: &automaticky (doporučeno)", "セグメント処理: 自動（推奨）(&A)", "分段操作：自动（推荐）(&A)", "分段作業：自動（建議）(&A)")
A("Select\r\nCtrl+Shift+S", "Selecionar\r\nCtrl+Shift+S", "Seleccionar\r\nCtrl+Shift+S", "Sélectionner\r\nCtrl+Shift+S", "Auswählen\r\nCtrl+Shift+S", "Seleziona\r\nCtrl+Shift+S", "Zaznacz\r\nCtrl+Shift+S", "Selectează\r\nCtrl+Shift+S", "Kijelölés\r\nCtrl+Shift+S", "Vybrat\r\nCtrl+Shift+S", "選択\r\nCtrl+Shift+S", "选择\r\nCtrl+Shift+S", "選擇\r\nCtrl+Shift+S")
A("Select\r\nskin", "Selecionar\r\nskin", "Seleccionar\r\nskin", "Choisir\r\nle skin", "Skin\r\nwählen", "Seleziona\r\nskin", "Wybierz\r\nskórkę", "Alege\r\nskin", "Skin\r\nválasztása", "Vybrat\r\nskin", "スキン\r\n選択", "选择\r\n皮肤", "選擇\r\n外觀")
A("Select Skin", "Selecionar skin", "Seleccionar skin", "Choisir le skin", "Skin wählen", "Seleziona skin", "Wybierz skórkę", "Alege skin", "Skin választása", "Vybrat skin", "スキンを選択", "选择皮肤", "選擇外觀")
A("Select lines to merge into one (current line stays as target).", "Selecione as linhas a mesclar em uma só (a linha atual permanece como destino).", "Seleccione las líneas que se combinarán en una (la línea actual queda como destino).", "Sélectionnez les lignes à fusionner en une seule (la ligne actuelle reste la cible).", "Wählen Sie Zeilen, die zu einer zusammengeführt werden (die aktuelle Zeile bleibt das Ziel).", "Seleziona le righe da unire in una (la riga corrente resta la destinazione).", "Zaznacz wiersze do scalenia w jeden (bieżący wiersz pozostaje docelowym).", "Selectați liniile de îmbinat într-una (linia curentă rămâne țintă).", "Jelölje ki az egy sorba egyesítendő sorokat (az aktuális sor marad a cél).", "Vyberte řádky ke sloučení do jednoho (aktuální řádek zůstává cílem).", "1 行に結合する行を選択してください（現在の行が結合先になります）。", "选择要合并为一行的行（当前行作为目标）。", "選擇要合併為一行的行（目前行作為目標）。")
A("Select skin", "Selecionar skin", "Seleccionar skin", "Choisir le skin", "Skin wählen", "Seleziona skin", "Wybierz skórkę", "Alege skin", "Skin választása", "Vybrat skin", "スキンを選択", "选择皮肤", "選擇外觀")
A("SelectSkin dialog", "Diálogo de seleção de skin", "Diálogo de selección de skin", "Boîte de dialogue de choix du skin", "Skin-Auswahldialog", "Finestra di selezione skin", "Okno wyboru skórki", "Dialog de selectare skin", "Skinválasztó párbeszédablak", "Dialog výběru skinu", "スキン選択ダイアログ", "皮肤选择对话框", "外觀選擇對話方塊")
A("Selected / checked lines only", "Somente linhas selecionadas / marcadas", "Solo líneas seleccionadas / marcadas", "Lignes sélectionnées / cochées uniquement", "Nur ausgewählte / markierte Zeilen", "Solo righe selezionate / spuntate", "Tylko zaznaczone wiersze", "Doar liniile selectate / bifate", "Csak kijelölt / bejelölt sorok", "Pouze vybrané / zaškrtnuté řádky", "選択 / チェックした行のみ", "仅所选 / 勾选的行", "僅所選 / 勾選的行")
A("Sending lines...", "Enviando linhas...", "Enviando líneas...", "Envoi des lignes...", "Zeilen werden gesendet...", "Invio righe...", "Wysyłanie wierszy...", "Se trimit liniile...", "Sorok küldése...", "Odesílání řádků...", "行を送信中...", "正在发送行...", "正在傳送行...")
A("Server returned HTTP status %d.", "O servidor retornou o status HTTP %d.", "El servidor devolvió el estado HTTP %d.", "Le serveur a renvoyé le statut HTTP %d.", "Der Server hat HTTP-Status %d zurückgegeben.", "Il server ha restituito lo stato HTTP %d.", "Serwer zwrócił status HTTP %d.", "Serverul a returnat starea HTTP %d.", "A kiszolgáló HTTP %d állapotot adott vissza.", "Server vrátil stav HTTP %d.", "サーバーが HTTP ステータス %d を返しました。", "服务器返回 HTTP 状态 %d。", "伺服器傳回 HTTP 狀態 %d。")
A("Session loaded.", "Sessão carregada.", "Sesión cargada.", "Session chargée.", "Sitzung geladen.", "Sessione caricata.", "Sesja wczytana.", "Sesiune încărcată.", "Munkamenet betöltve.", "Relace načtena.", "セッションを読み込みました。", "会话已加载。", "工作階段已載入。")
A("Session saved.", "Sessão salva.", "Sesión guardada.", "Session enregistrée.", "Sitzung gespeichert.", "Sessione salvata.", "Sesja zapisana.", "Sesiune salvată.", "Munkamenet mentve.", "Relace uložena.", "セッションを保存しました。", "会话已保存。", "工作階段已儲存。")
A("Short Overview", "Visão geral", "Resumen", "Aperçu", "Kurzübersicht", "Panoramica", "Krótki przegląd", "Prezentare scurtă", "Rövid áttekintés", "Stručný přehled", "概要", "简要概述", "簡要概述")
A("Show CheckBoxes", "Mostrar caixas de seleção", "Mostrar casillas", "Afficher les cases à cocher", "Kontrollkästchen anzeigen", "Mostra caselle di controllo", "Pokaż pola wyboru", "Afișează casetele de bifare", "Jelölőnégyzetek megjelenítése", "Zobrazit zaškrtávací políčka", "チェックボックスを表示", "显示复选框", "顯示核取方塊")
A("Show Hints", "Mostrar dicas", "Mostrar sugerencias", "Afficher les info-bulles", "Hinweise anzeigen", "Mostra suggerimenti", "Pokaż podpowiedzi", "Afișează indicii", "Tippek megjelenítése", "Zobrazit tipy", "ヒントを表示", "显示提示", "顯示提示")
A("Show hover hints on lines and on all controls", "Mostrar dicas ao passar o mouse nas linhas e em todos os controles", "Mostrar sugerencias al pasar el ratón por las líneas y todos los controles", "Afficher les info-bulles de survol sur les lignes et tous les contrôles", "Hover-Hinweise auf Zeilen und allen Steuerelementen anzeigen", "Mostra suggerimenti al passaggio del mouse su righe e controlli", "Pokaż podpowiedzi po najechaniu na wiersze i wszystkie kontrolki", "Afișează indicii la trecerea mouse-ului peste linii și toate controalele", "Tippek megjelenítése a sorok és minden vezérlő fölött", "Zobrazovat tipy při najetí na řádky a všechny ovládací prvky", "行とすべてのコントロールにホバーヒントを表示", "在行和所有控件上显示悬停提示", "在行和所有控制項上顯示暫留提示")
A("Show/hide app icon", "Mostrar/ocultar ícone do aplicativo", "Mostrar/ocultar icono de la aplicación", "Afficher/masquer l'icône de l'application", "App-Symbol ein-/ausblenden", "Mostra/nascondi icona dell'app", "Pokaż/ukryj ikonę aplikacji", "Afișează/ascunde pictograma aplicației", "Alkalmazásikon megjelenítése/elrejtése", "Zobrazit/skrýt ikonu aplikace", "アプリのアイコンを表示/非表示", "显示/隐藏应用图标", "顯示/隱藏應用程式圖示")
A("Skinned", "Com skin", "Con skin", "Avec skin", "Mit Skin", "Con skin", "Ze skórką", "Cu skin", "Skinnel", "Se skinem", "スキン適用", "应用皮肤", "套用外觀")
A("Specifications", "Especificações", "Especificaciones", "Spécifications", "Spezifikationen", "Specifiche", "Specyfikacja", "Specificații", "Műszaki adatok", "Specifikace", "仕様", "规格", "規格")
A("Split", "Dividir", "Dividir", "Découper", "Aufteilen", "Dividi", "Podziel", "Împarte", "Felosztás", "Rozdělit", "分割", "拆分", "分割")
A("Split - start a new file when a delimiter-separated token appears", "Dividir - iniciar um novo arquivo quando surgir um token separado por delimitador", "Dividir - iniciar un nuevo archivo cuando aparezca un token separado por delimitador", "Découper - démarrer un nouveau fichier quand un jeton séparé par délimiteur apparaît", "Aufteilen - neue Datei beginnen, wenn ein trennzeichengetrenntes Token erscheint", "Dividi - avvia un nuovo file quando compare un token separato da delimitatore", "Podziel - rozpocznij nowy plik, gdy pojawi się token rozdzielony separatorem", "Împarte - începe un fișier nou când apare un token separat prin delimitator", "Felosztás - új fájl kezdése, ha elválasztóval határolt token jelenik meg", "Rozdělit - začít nový soubor, když se objeví token oddělený oddělovačem", "分割 - 区切り文字で区切られたトークンが現れたら新しいファイルを開始", "拆分 - 出现分隔符分隔的标记时开始新文件", "分割 - 出現分隔符號分隔的標記時開始新檔案")
A("Split Files\r\nCtrl+Shift+K", "Dividir arquivos\r\nCtrl+Shift+K", "Dividir archivos\r\nCtrl+Shift+K", "Découper des fichiers\r\nCtrl+Shift+K", "Dateien aufteilen\r\nCtrl+Shift+K", "Dividi file\r\nCtrl+Shift+K", "Podziel pliki\r\nCtrl+Shift+K", "Împarte fișiere\r\nCtrl+Shift+K", "Fájlok felosztása\r\nCtrl+Shift+K", "Rozdělit soubory\r\nCtrl+Shift+K", "ファイルを分割\r\nCtrl+Shift+K", "拆分文件\r\nCtrl+Shift+K", "分割檔案\r\nCtrl+Shift+K")
A("Split by Pattern/Regex", "Dividir por padrão/regex", "Dividir por patrón/regex", "Découper par motif/regex", "Nach Muster/Regex aufteilen", "Dividi per schema/regex", "Podziel według wzorca/regex", "Împarte după șablon/regex", "Felosztás minta/regex szerint", "Rozdělit podle vzoru/regexu", "パターン/正規表現で分割", "按模式/正则拆分", "依模式/正則分割")
A("Split into Equal Parts", "Dividir em partes iguais", "Dividir en partes iguales", "Découper en parts égales", "In gleiche Teile aufteilen", "Dividi in parti uguali", "Podziel na równe części", "Împarte în părți egale", "Felosztás egyenlő részekre", "Rozdělit na stejné části", "均等に分割", "拆分为等份", "分割為等份")
A("Split mode opens a new output file at every line where Test(regex) is true - tighten the wildcards so only real boundaries match.",
  "O modo Dividir abre um novo arquivo de saída em cada linha em que Test(regex) é verdadeiro - restrinja os curingas para que apenas os limites reais correspondam.",
  "El modo Dividir abre un nuevo archivo de salida en cada línea en la que Test(regex) es verdadero: ajuste los comodines para que solo coincidan los límites reales.",
  "Le mode Découpage ouvre un nouveau fichier de sortie à chaque ligne où Test(regex) est vrai - resserrez les jokers pour ne correspondre qu'aux vraies limites.",
  "Der Aufteilungsmodus öffnet an jeder Zeile, an der Test(regex) wahr ist, eine neue Ausgabedatei - Platzhalter so eng fassen, dass nur echte Grenzen passen.",
  "La modalità Divisione apre un nuovo file di output a ogni riga in cui Test(regex) è vero - restringi i caratteri jolly in modo che corrispondano solo i confini reali.",
  "Tryb Podziału otwiera nowy plik wyjściowy w każdym wierszu, w którym Test(regex) jest prawdziwy - zawęź symbole wieloznaczne, aby pasowały tylko rzeczywiste granice.",
  "Modul Împărțire deschide un fișier de ieșire nou la fiecare linie în care Test(regex) este adevărat - restrângeți metacaracterele ca să se potrivească doar limitele reale.",
  "Felosztás módban minden olyan sornál új kimeneti fájl nyílik, ahol a Test(regex) igaz - szűkítse a helyettesítő karaktereket, hogy csak a valódi határok illeszkedjenek.",
  "Režim Rozdělit otevře nový výstupní soubor na každém řádku, kde je Test(regex) pravdivý - zužte zástupné znaky, aby odpovídaly jen skutečné hranice.",
  "分割モードでは Test(regex) が真になる各行で新しい出力ファイルを開きます。実際の境界のみに一致するようワイルドカードを絞り込んでください。",
  "拆分模式会在 Test(regex) 为真的每一行打开新的输出文件——请收紧通配符，使其只匹配真正的边界。",
  "分割模式會在 Test(regex) 為真的每一行開啟新的輸出檔案——請收緊萬用字元，使其只比對真正的邊界。")
A("Split: equal parts (N parts, preserving complete lines)", "Dividir: partes iguais (N partes, preservando linhas completas)", "Dividir: partes iguales (N partes, conservando líneas completas)", "Découper : parts égales (N parts, lignes complètes conservées)", "Aufteilen: gleiche Teile (N Teile, vollständige Zeilen bleiben erhalten)", "Dividi: parti uguali (N parti, righe complete preservate)", "Podziel: równe części (N części, z zachowaniem pełnych wierszy)", "Împarte: părți egale (N părți, cu păstrarea liniilor complete)", "Felosztás: egyenlő részek (N rész, teljes sorok megtartásával)", "Rozdělit: stejné části (N částí, se zachováním celých řádků)", "分割: 均等（N パート、行を分断しない）", "拆分：等份（N 份，保留完整行）", "分割：等份（N 份，保留完整行）")
A("Split: start a new file when a line matches (pattern/regex)", "Dividir: iniciar um novo arquivo quando uma linha corresponder (padrão/regex)", "Dividir: iniciar un nuevo archivo cuando una línea coincida (patrón/regex)", "Découper : démarrer un nouveau fichier quand une ligne correspond (motif/regex)", "Aufteilen: neue Datei beginnen, wenn eine Zeile passt (Muster/Regex)", "Dividi: avvia un nuovo file quando una riga corrisponde (schema/regex)", "Podziel: rozpocznij nowy plik, gdy wiersz pasuje (wzorzec/regex)", "Împarte: începe un fișier nou când o linie se potrivește (șablon/regex)", "Felosztás: új fájl kezdése, ha egy sor illeszkedik (minta/regex)", "Rozdělit: začít nový soubor, když řádek odpovídá (vzor/regex)", "分割: 行が一致したら新しいファイルを開始（パターン/正規表現）", "拆分：行匹配时开始新文件（模式/正则）", "分割：行相符時開始新檔案（模式/正則）")
A("Stable Version:\r\n\r\nCompatible Windows versions:\r\nSupported platforms:", "Versão estável:\r\n\r\nVersões do Windows compatíveis:\r\nPlataformas suportadas:", "Versión estable:\r\n\r\nVersiones de Windows compatibles:\r\nPlataformas compatibles:", "Version stable :\r\n\r\nVersions de Windows compatibles :\r\nPlateformes prises en charge :", "Stabile Version:\r\n\r\nKompatible Windows-Versionen:\r\nUnterstützte Plattformen:", "Versione stabile:\r\n\r\nVersioni di Windows compatibili:\r\nPiattaforme supportate:", "Wersja stabilna:\r\n\r\nZgodne wersje Windows:\r\nObsługiwane platformy:", "Versiune stabilă:\r\n\r\nVersiuni Windows compatibile:\r\nPlatforme acceptate:", "Stabil verzió:\r\n\r\nKompatibilis Windows-verziók:\r\nTámogatott platformok:", "Stabilní verze:\r\n\r\nKompatibilní verze Windows:\r\nPodporované platformy:", "安定版:\r\n\r\n対応 Windows バージョン:\r\n対応プラットフォーム:", "稳定版本：\r\n\r\n兼容的 Windows 版本：\r\n支持的平台：", "穩定版本：\r\n\r\n相容的 Windows 版本：\r\n支援的平台：")
A("Standard", "Padrão", "Estándar", "Standard", "Standard", "Standard", "Standardowy", "Standard", "Normál", "Standardní", "標準", "标准", "標準")
A("Stop\r\nanimation", "Parar\r\nanimação", "Detener\r\nanimación", "Arrêter\r\nl'animation", "Animation\r\nstoppen", "Ferma\r\nanimazione", "Zatrzymaj\r\nanimację", "Oprește\r\nanimația", "Animáció\r\nleállítása", "Zastavit\r\nanimaci", "アニメーション\r\n停止", "停止\r\n动画", "停止\r\n動畫")
