# Order: key, PT, ES, FR, DE, IT, PL, RO, HU, CZ, JA, ZHCN, ZHTW
A("Tail OFF", "Tail DESLIGADO", "Tail DESACTIVADO", "Suivi DÉSACTIVÉ", "Tail AUS", "Tail DISATTIVO", "Tail WYŁ.", "Tail OPRIT", "Tail KI", "Tail VYP", "テイル オフ", "尾随 关", "尾隨 關")
A("Tail ON", "Tail LIGADO", "Tail ACTIVADO", "Suivi ACTIVÉ", "Tail EIN", "Tail ATTIVO", "Tail WŁ.", "Tail PORNIT", "Tail BE", "Tail ZAP", "テイル オン", "尾随 开", "尾隨 開")
A("Tail PAUSED", "Tail PAUSADO", "Tail EN PAUSA", "Suivi EN PAUSE", "Tail PAUSIERT", "Tail IN PAUSA", "Tail WSTRZYMANY", "Tail ÎN PAUZĂ", "Tail SZÜNETEL", "Tail POZASTAVEN", "テイル 一時停止", "尾随 已暂停", "尾隨 已暫停")
A("Tail PAUSED +%d new lines", "Tail PAUSADO +%d novas linhas", "Tail EN PAUSA +%d líneas nuevas", "Suivi EN PAUSE +%d nouvelles lignes", "Tail PAUSIERT +%d neue Zeilen", "Tail IN PAUSA +%d nuove righe", "Tail WSTRZYMANY +%d nowych wierszy", "Tail ÎN PAUZĂ +%d linii noi", "Tail SZÜNETEL +%d új sor", "Tail POZASTAVEN +%d nových řádků", "テイル 一時停止 +%d 行の新規行", "尾随 已暂停 +%d 新行", "尾隨 已暫停 +%d 新行")
A("Tail captured 0 line(s).", "Tail capturou 0 linha(s).", "Tail capturó 0 línea(s).", "Le suivi a capturé 0 ligne(s).", "Tail hat 0 Zeile(n) erfasst.", "Tail ha catturato 0 righe.", "Tail przechwycił 0 wierszy.", "Tail a capturat 0 linii.", "A tail 0 sort rögzített.", "Tail zachytil 0 řádků.", "テイルで 0 行を取得しました。", "尾随捕获了 0 行。", "尾隨擷取了 0 行。")
A("Tail is OFF - press Ctrl+T to follow the file again.", "O Tail está DESLIGADO - pressione Ctrl+T para acompanhar o arquivo novamente.", "Tail está DESACTIVADO: pulse Ctrl+T para volver a seguir el archivo.", "Le suivi est DÉSACTIVÉ - appuyez sur Ctrl+T pour suivre à nouveau le fichier.", "Tail ist AUS - Strg+T drücken, um der Datei wieder zu folgen.", "Tail è DISATTIVO - premi Ctrl+T per seguire di nuovo il file.", "Tail jest WYŁĄCZONY - naciśnij Ctrl+T, aby ponownie śledzić plik.", "Tail este OPRIT - apăsați Ctrl+T pentru a urmări din nou fișierul.", "A tail KI van kapcsolva - nyomja meg a Ctrl+T billentyűt a fájl újbóli követéséhez.", "Tail je VYPNUTÝ - stiskněte Ctrl+T pro opětovné sledování souboru.", "テイルはオフです。Ctrl+T を押すと再びファイルを追跡します。", "尾随已关闭——按 Ctrl+T 重新跟随文件。", "尾隨已關閉——按 Ctrl+T 重新跟隨檔案。")
A("Tail is ON - new lines at end of file are followed.", "O Tail está LIGADO - novas linhas no fim do arquivo são acompanhadas.", "Tail está ACTIVADO: se siguen las nuevas líneas al final del archivo.", "Le suivi est ACTIVÉ - les nouvelles lignes en fin de fichier sont suivies.", "Tail ist EIN - neue Zeilen am Dateiende werden verfolgt.", "Tail è ATTIVO - le nuove righe a fine file vengono seguite.", "Tail jest WŁĄCZONY - nowe wiersze na końcu pliku są śledzone.", "Tail este PORNIT - liniile noi de la sfârșitul fișierului sunt urmărite.", "A tail BE van kapcsolva - a fájl végén megjelenő új sorokat követi.", "Tail je ZAPNUTÝ - nové řádky na konci souboru jsou sledovány.", "テイルはオンです。ファイル末尾の新しい行を追跡します。", "尾随已开启——将跟随文件末尾的新行。", "尾隨已開啟——將跟隨檔案結尾的新行。")
A("Tail macro: chunk done, %d OK - next chunk...", "Macro tail: bloco concluído, %d OK - próximo bloco...", "Macro tail: bloque terminado, %d OK - siguiente bloque...", "Macro de suivi : bloc terminé, %d OK - bloc suivant...", "Tail-Makro: Block fertig, %d OK - nächster Block...", "Macro tail: blocco completato, %d OK - blocco successivo...", "Makro tail: blok gotowy, %d OK - następny blok...", "Macro tail: bloc terminat, %d OK - blocul următor...", "Tail makró: blokk kész, %d OK - következő blokk...", "Makro tail: blok hotov, %d OK - další blok...", "テイルマクロ: チャンク完了、%d 件 OK - 次のチャンク...", "尾随宏：块完成，%d 个成功——下一块...", "尾隨巨集：區塊完成，%d 個成功——下一區塊...")
A("Tail macro: index file temp.txt not found - read the file (F5) first.", "Macro tail: arquivo de índice temp.txt não encontrado - leia o arquivo (F5) primeiro.", "Macro tail: no se encontró el archivo de índice temp.txt; lea primero el archivo (F5).", "Macro de suivi : fichier d'index temp.txt introuvable - lisez d'abord le fichier (F5).", "Tail-Makro: Indexdatei temp.txt nicht gefunden - lesen Sie zuerst die Datei (F5).", "Macro tail: file indice temp.txt non trovato - leggi prima il file (F5).", "Makro tail: nie znaleziono pliku indeksu temp.txt - najpierw wczytaj plik (F5).", "Macro tail: fișierul index temp.txt nu a fost găsit - citiți mai întâi fișierul (F5).", "Tail makró: a temp.txt indexfájl nem található - előbb olvassa be a fájlt (F5).", "Makro tail: indexový soubor temp.txt nenalezen - nejprve načtěte soubor (F5).", "テイルマクロ: インデックスファイル temp.txt が見つかりません。先にファイルを読み込んでください (F5)。", "尾随宏：未找到索引文件 temp.txt——请先读取文件 (F5)。", "尾隨巨集：找不到索引檔 temp.txt——請先讀取檔案 (F5)。")
A("Targets Dr./Dra. patterns together with the following name field (%s). VBScript-safe (no lookbehind).",
  "Localiza padrões Dr./Dra. junto com o campo de nome seguinte (%s). Compatível com VBScript (sem lookbehind).",
  "Busca patrones Dr./Dra. junto con el campo de nombre siguiente (%s). Compatible con VBScript (sin lookbehind).",
  "Cible les motifs Dr./Dra. avec le champ de nom qui suit (%s). Compatible VBScript (sans lookbehind).",
  "Zielt auf Dr./Dra.-Muster zusammen mit dem folgenden Namensfeld (%s). VBScript-sicher (kein Lookbehind).",
  "Individua schemi Dr./Dra. insieme al campo nome successivo (%s). Compatibile con VBScript (niente lookbehind).",
  "Wyszukuje wzorce Dr./Dra. wraz z następującym polem nazwiska (%s). Zgodne z VBScript (bez lookbehind).",
  "Vizează șabloanele Dr./Dra. împreună cu câmpul de nume următor (%s). Compatibil VBScript (fără lookbehind).",
  "A Dr./Dra. mintákat és az utánuk következő névmezőt (%s) célozza. VBScript-kompatibilis (nincs lookbehind).",
  "Cílí na vzory Dr./Dra. spolu s následujícím polem jména (%s). Bezpečné pro VBScript (bez lookbehind).",
  "Dr./Dra. のパターンと、それに続く名前フィールド (%s) を対象にします。VBScript 対応（後読みなし）。",
  "匹配 Dr./Dra. 模式及其后的姓名字段 (%s)。兼容 VBScript（无后行断言）。",
  "比對 Dr./Dra. 模式及其後的姓名欄位 (%s)。相容 VBScript（無後行斷言）。")
A("Test writes true or false per input line - ideal for quickly validating row types.",
  "Test grava true ou false para cada linha de entrada - ideal para validar rapidamente tipos de registro.", "Test escribe true o false por cada línea de entrada: ideal para validar rápidamente tipos de fila.",
  "Test écrit true ou false pour chaque ligne d'entrée - idéal pour valider rapidement les types de lignes.", "Test schreibt pro Eingabezeile true oder false - ideal zur schnellen Prüfung von Zeilentypen.",
  "Test scrive true o false per ogni riga di input - ideale per convalidare rapidamente i tipi di riga.", "Test zapisuje true lub false dla każdego wiersza wejściowego - idealne do szybkiej weryfikacji typów wierszy.",
  "Test scrie true sau false pentru fiecare linie de intrare - ideal pentru validarea rapidă a tipurilor de rânduri.", "A Test minden bemeneti sorhoz true vagy false értéket ír - ideális a sortípusok gyors ellenőrzéséhez.",
  "Test zapíše true nebo false pro každý vstupní řádek - ideální pro rychlé ověření typů řádků.", "Test は入力行ごとに true または false を書き込みます。行の種類をすばやく検証するのに最適です。",
  "Test 为每个输入行写入 true 或 false——非常适合快速验证行类型。", "Test 為每個輸入行寫入 true 或 false——非常適合快速驗證行類型。")
A("Text", "Texto", "Texto", "Texte", "Text", "Testo", "Tekst", "Text", "Szöveg", "Text", "テキスト", "文本", "文字")
A("Text files (*.txt)", "Arquivos de texto (*.txt)", "Archivos de texto (*.txt)", "Fichiers texte (*.txt)", "Textdateien (*.txt)", "File di testo (*.txt)", "Pliki tekstowe (*.txt)", "Fișiere text (*.txt)", "Szövegfájlok (*.txt)", "Textové soubory (*.txt)", "テキストファイル (*.txt)", "文本文件 (*.txt)", "文字檔 (*.txt)")
A("Text not found.", "Texto não encontrado.", "Texto no encontrado.", "Texte introuvable.", "Text nicht gefunden.", "Testo non trovato.", "Nie znaleziono tekstu.", "Textul nu a fost găsit.", "A szöveg nem található.", "Text nenalezen.", "テキストが見つかりません。", "未找到文本。", "找不到文字。")
A("The last eight digits of the final digit island on the first line look like %s (often a DDMMYYYY-style date).",
  "Os últimos oito dígitos do último bloco numérico da primeira linha parecem ser %s (frequentemente uma data no estilo DDMMAAAA).",
  "Los últimos ocho dígitos del último bloque numérico de la primera línea parecen %s (a menudo una fecha tipo DDMMAAAA).",
  "Les huit derniers chiffres du dernier bloc numérique de la première ligne ressemblent à %s (souvent une date au format JJMMAAAA).",
  "Die letzten acht Ziffern des letzten Ziffernblocks in der ersten Zeile sehen aus wie %s (oft ein Datum im Stil TTMMJJJJ).",
  "Le ultime otto cifre dell'ultimo blocco numerico della prima riga sembrano %s (spesso una data in stile GGMMAAAA).",
  "Ostatnie osiem cyfr ostatniego bloku cyfr w pierwszym wierszu wygląda jak %s (często data w stylu DDMMRRRR).",
  "Ultimele opt cifre ale ultimului bloc numeric de pe prima linie arată ca %s (adesea o dată de tip ZZLLAAAA).",
  "Az első sor utolsó számblokkjának utolsó nyolc számjegye %s-nek tűnik (gyakran NNHHÉÉÉÉ stílusú dátum).",
  "Posledních osm číslic posledního číselného bloku na prvním řádku vypadá jako %s (často datum ve stylu DDMMRRRR).",
  "1 行目の最後の数字ブロックの末尾 8 桁は %s のようです（多くの場合 DDMMYYYY 形式の日付）。",
  "第一行最后一段数字的末尾八位看起来像 %s（通常是 DDMMYYYY 格式的日期）。",
  "第一行最後一段數字的末尾八位看起來像 %s（通常是 DDMMYYYY 格式的日期）。")
A("This file is very large. The app will skip the full pre-scan (counting matches) to keep the UI responsive.",
  "Este arquivo é muito grande. O aplicativo vai pular a pré-varredura completa (contagem de correspondências) para manter a interface responsiva.",
  "Este archivo es muy grande. La aplicación omitirá el análisis previo completo (conteo de coincidencias) para mantener la interfaz fluida.",
  "Ce fichier est très volumineux. L'application ignorera la pré-analyse complète (comptage des correspondances) pour garder l'interface réactive.",
  "Diese Datei ist sehr groß. Die Anwendung überspringt den vollständigen Vorabscan (Trefferzählung), damit die Oberfläche reaktionsfähig bleibt.",
  "Questo file è molto grande. L'applicazione salterà la pre-scansione completa (conteggio delle corrispondenze) per mantenere reattiva l'interfaccia.",
  "Ten plik jest bardzo duży. Aplikacja pominie pełne wstępne skanowanie (liczenie dopasowań), aby interfejs pozostał responsywny.",
  "Acest fișier este foarte mare. Aplicația va omite scanarea prealabilă completă (numărarea potrivirilor) pentru a păstra interfața reactivă.",
  "Ez a fájl nagyon nagy. Az alkalmazás kihagyja a teljes előzetes vizsgálatot (találatok számlálása), hogy a felület reszponzív maradjon.",
  "Tento soubor je velmi velký. Aplikace přeskočí úplné předběžné prohledání (počítání shod), aby rozhraní zůstalo svižné.",
  "このファイルは非常に大きいため、UI の応答性を保つために完全な事前スキャン（一致数のカウント）を省略します。",
  "此文件非常大。为保持界面响应，程序将跳过完整预扫描（统计匹配数）。",
  "此檔案非常大。為維持介面回應，程式將略過完整預先掃描（統計相符數）。")
A("To split into N equal parts by line count or size, use FastFile's equal-parts workflow instead of Regex - Regex cannot count lines across the whole file in one Test call.",
  "Para dividir em N partes iguais por número de linhas ou tamanho, use o recurso de partes iguais do FastFile em vez de Regex - o Regex não consegue contar linhas do arquivo inteiro em uma única chamada Test.",
  "Para dividir en N partes iguales por número de líneas o tamaño, use el flujo de partes iguales de FastFile en lugar de Regex: Regex no puede contar las líneas de todo el archivo en una sola llamada Test.",
  "Pour découper en N parts égales par nombre de lignes ou taille, utilisez la fonction parts égales de FastFile plutôt que Regex - Regex ne peut pas compter les lignes de tout le fichier en un seul appel Test.",
  "Um nach Zeilenanzahl oder Größe in N gleiche Teile aufzuteilen, verwenden Sie FastFiles Gleiche-Teile-Funktion statt Regex - Regex kann in einem Test-Aufruf nicht die Zeilen der ganzen Datei zählen.",
  "Per dividere in N parti uguali per numero di righe o dimensione, usa la funzione parti uguali di FastFile invece di Regex - Regex non può contare le righe dell'intero file in una sola chiamata Test.",
  "Aby podzielić na N równych części według liczby wierszy lub rozmiaru, użyj funkcji równych części FastFile zamiast Regex - Regex nie policzy wierszy całego pliku w jednym wywołaniu Test.",
  "Pentru a împărți în N părți egale după numărul de linii sau dimensiune, folosiți funcția părți egale din FastFile în loc de Regex - Regex nu poate număra liniile întregului fișier într-un singur apel Test.",
  "N egyenlő részre sorszám vagy méret szerint a FastFile egyenlő részek funkcióját használja Regex helyett - a Regex egyetlen Test hívással nem tudja megszámolni a teljes fájl sorait.",
  "Pro rozdělení na N stejných částí podle počtu řádků nebo velikosti použijte místo Regexu funkci stejných částí FastFile - Regex nedokáže v jednom volání Test spočítat řádky celého souboru.",
  "行数やサイズで N 等分するには、正規表現ではなく FastFile の均等分割機能を使用してください。正規表現では 1 回の Test 呼び出しでファイル全体の行数を数えられません。",
  "若要按行数或大小拆分为 N 等份，请使用 FastFile 的等分功能而非正则——正则无法在一次 Test 调用中统计整个文件的行数。",
  "若要依行數或大小分割為 N 等份，請使用 FastFile 的等分功能而非正則——正則無法在一次 Test 呼叫中統計整個檔案的行數。")
A("Toggle Word Wrap (Ctrl+W)", "Alternar quebra de linha (Ctrl+W)", "Alternar ajuste de línea (Ctrl+W)", "Activer/désactiver le retour à la ligne (Ctrl+W)", "Zeilenumbruch umschalten (Strg+W)", "Attiva/disattiva a capo automatico (Ctrl+W)", "Przełącz zawijanie wierszy (Ctrl+W)", "Comută încadrarea textului (Ctrl+W)", "Sortörés be/ki (Ctrl+W)", "Přepnout zalamování řádků (Ctrl+W)", "折り返しの切り替え (Ctrl+W)", "切换自动换行 (Ctrl+W)", "切換自動換行 (Ctrl+W)")
A("Tools", "Ferramentas", "Herramientas", "Outils", "Werkzeuge", "Strumenti", "Narzędzia", "Instrumente", "Eszközök", "Nástroje", "ツール", "工具", "工具")
A("Top toolbar", "Barra de ferramentas superior", "Barra de herramientas superior", "Barre d'outils supérieure", "Obere Symbolleiste", "Barra degli strumenti superiore", "Górny pasek narzędzi", "Bara de instrumente de sus", "Felső eszköztár", "Horní panel nástrojů", "上部ツールバー", "顶部工具栏", "頂端工具列")
A("Tutorials: ", "Tutoriais: ", "Tutoriales: ", "Tutoriels : ", "Tutorials: ", "Tutorial: ", "Samouczki: ", "Tutoriale: ", "Oktatóanyagok: ", "Návody: ", "チュートリアル: ", "教程：", "教學：")
A("Typed text:", "Texto digitado:", "Texto escrito:", "Texte saisi :", "Eingegebener Text:", "Testo digitato:", "Wpisany tekst:", "Text introdus:", "Beírt szöveg:", "Zadaný text:", "入力したテキスト:", "输入的文本：", "輸入的文字：")
A("Useful links:", "Links úteis:", "Enlaces útiles:", "Liens utiles :", "Nützliche Links:", "Link utili:", "Przydatne linki:", "Linkuri utile:", "Hasznos hivatkozások:", "Užitečné odkazy:", "便利なリンク:", "有用的链接：", "實用連結：")
A("Useful to sample IDs and amounts embedded between runs of zeros.", "Útil para amostrar IDs e valores embutidos entre sequências de zeros.", "Útil para muestrear ID e importes incrustados entre secuencias de ceros.", "Utile pour échantillonner des identifiants et montants noyés entre des suites de zéros.", "Nützlich, um IDs und Beträge zwischen Nullfolgen zu erfassen.", "Utile per campionare ID e importi inseriti tra sequenze di zeri.", "Przydatne do wyszukiwania identyfikatorów i kwot osadzonych między ciągami zer.", "Util pentru eșantionarea ID-urilor și sumelor încadrate între secvențe de zerouri.", "Hasznos a nullasorozatok közé ágyazott azonosítók és összegek mintavételéhez.", "Užitečné pro vzorkování ID a částek vložených mezi posloupnosti nul.", "ゼロの連続に挟まれた ID や金額をサンプリングするのに便利です。", "适用于抽取夹在连续零之间的 ID 和金额。", "適用於擷取夾在連續零之間的 ID 與金額。")
A("Useful when a column stores URLs; anchors may need quotes or extra delimiters for your file.", "Útil quando uma coluna armazena URLs; as âncoras podem precisar de aspas ou delimitadores extras para o seu arquivo.", "Útil cuando una columna almacena URL; los anclajes pueden necesitar comillas o delimitadores adicionales en su archivo.", "Utile quand une colonne contient des URL ; les ancres peuvent nécessiter des guillemets ou des délimiteurs supplémentaires selon votre fichier.", "Nützlich, wenn eine Spalte URLs enthält; Anker benötigen je nach Datei ggf. Anführungszeichen oder zusätzliche Trennzeichen.", "Utile quando una colonna contiene URL; le ancore potrebbero richiedere virgolette o delimitatori aggiuntivi per il tuo file.", "Przydatne, gdy kolumna zawiera adresy URL; kotwice mogą wymagać cudzysłowów lub dodatkowych separatorów w Twoim pliku.", "Util când o coloană stochează URL-uri; ancorele pot necesita ghilimele sau delimitatori suplimentari pentru fișierul dvs.", "Hasznos, ha egy oszlop URL-eket tárol; a horgonyokhoz a fájltól függően idézőjel vagy további elválasztó kellhet.", "Užitečné, když sloupec obsahuje URL; kotvy mohou ve vašem souboru vyžadovat uvozovky nebo další oddělovače.", "列に URL が格納されている場合に便利です。ファイルによってはアンカーに引用符や追加の区切り文字が必要です。", "适用于列中存储 URL 的情况；根据文件不同，锚点可能需要引号或额外的分隔符。", "適用於欄位中儲存 URL 的情況；依檔案不同，錨點可能需要引號或額外的分隔符號。")
A("View: UTF-32 BE", "Exibição: UTF-32 BE", "Vista: UTF-32 BE", "Vue : UTF-32 BE", "Ansicht: UTF-32 BE", "Vista: UTF-32 BE", "Widok: UTF-32 BE", "Vizualizare: UTF-32 BE", "Nézet: UTF-32 BE", "Zobrazení: UTF-32 BE", "表示: UTF-32 BE", "视图：UTF-32 BE", "檢視：UTF-32 BE")
A("View: UTF-32 LE", "Exibição: UTF-32 LE", "Vista: UTF-32 LE", "Vue : UTF-32 LE", "Ansicht: UTF-32 LE", "Vista: UTF-32 LE", "Widok: UTF-32 LE", "Vizualizare: UTF-32 LE", "Nézet: UTF-32 LE", "Zobrazení: UTF-32 LE", "表示: UTF-32 LE", "视图：UTF-32 LE", "檢視：UTF-32 LE")
A("Waiting engine output...", "Aguardando saída do mecanismo...", "Esperando la salida del motor...", "En attente de la sortie du moteur...", "Warte auf Engine-Ausgabe...", "In attesa dell'output del motore...", "Oczekiwanie na wynik silnika...", "Se așteaptă ieșirea motorului...", "Várakozás a motor kimenetére...", "Čekání na výstup enginu...", "エンジンの出力を待機中...", "正在等待引擎输出...", "正在等待引擎輸出...")
A("Word Wrap (ON)", "Quebra de linha (LIGADA)", "Ajuste de línea (ACTIVADO)", "Retour à la ligne (ACTIVÉ)", "Zeilenumbruch (EIN)", "A capo automatico (ATTIVO)", "Zawijanie wierszy (WŁ.)", "Încadrare text (PORNITĂ)", "Sortörés (BE)", "Zalamování řádků (ZAP)", "折り返し（オン）", "自动换行（开）", "自動換行（開）")
A("Write", "Gravar", "Escribir", "Écrire", "Schreiben", "Scrivi", "Zapisz", "Scrie", "Írás", "Zapsat", "書き込み", "写入", "寫入")
A("YES = build line index now (full disk pass, exact line numbers).", "SIM = criar o índice de linhas agora (leitura completa do disco, números de linha exatos).", "SÍ = crear el índice de líneas ahora (lectura completa del disco, números de línea exactos).", "OUI = créer l'index des lignes maintenant (passage complet sur le disque, numéros de ligne exacts).", "JA = Zeilenindex jetzt erstellen (vollständiger Plattendurchlauf, exakte Zeilennummern).", "SÌ = crea ora l'indice delle righe (passata completa su disco, numeri di riga esatti).", "TAK = zbuduj teraz indeks wierszy (pełny odczyt dysku, dokładne numery wierszy).", "DA = creează acum indexul de linii (parcurgere completă a discului, numere de linie exacte).", "IGEN = sorindex létrehozása most (teljes lemezolvasás, pontos sorszámok).", "ANO = vytvořit index řádků nyní (úplný průchod diskem, přesná čísla řádků).", "はい = 今すぐ行インデックスを作成（ディスク全体を走査、正確な行番号）。", "是 = 立即建立行索引（完整扫描磁盘，精确行号）。", "是 = 立即建立行索引（完整掃描磁碟，精確行號）。")
A("YES = build line index now (recommended).", "SIM = criar o índice de linhas agora (recomendado).", "SÍ = crear el índice de líneas ahora (recomendado).", "OUI = créer l'index des lignes maintenant (recommandé).", "JA = Zeilenindex jetzt erstellen (empfohlen).", "SÌ = crea ora l'indice delle righe (consigliato).", "TAK = zbuduj teraz indeks wierszy (zalecane).", "DA = creează acum indexul de linii (recomandat).", "IGEN = sorindex létrehozása most (ajánlott).", "ANO = vytvořit index řádků nyní (doporučeno).", "はい = 今すぐ行インデックスを作成（推奨）。", "是 = 立即建立行索引（推荐）。", "是 = 立即建立行索引（建議）。")
A("You can use the Preview button in the dialog to sample matches quickly.", "Você pode usar o botão Pré-visualizar no diálogo para amostrar correspondências rapidamente.", "Puede usar el botón Vista previa del diálogo para muestrear coincidencias rápidamente.", "Vous pouvez utiliser le bouton Aperçu de la boîte de dialogue pour échantillonner rapidement les correspondances.", "Mit der Schaltfläche Vorschau im Dialog können Sie Treffer schnell stichprobenartig prüfen.", "Puoi usare il pulsante Anteprima nella finestra per campionare rapidamente le corrispondenze.", "Możesz użyć przycisku Podgląd w oknie, aby szybko pobrać próbkę dopasowań.", "Puteți folosi butonul Previzualizare din dialog pentru a eșantiona rapid potrivirile.", "A párbeszédablak Előnézet gombjával gyorsan mintát vehet a találatokból.", "Pomocí tlačítka Náhled v dialogu můžete rychle vzorkovat shody.", "ダイアログの [プレビュー] ボタンで一致をすばやくサンプリングできます。", "可以使用对话框中的“预览”按钮快速抽样匹配项。", "可以使用對話方塊中的「預覽」按鈕快速抽樣相符項。")
A("Your first line begins with sixteen consecutive digits. They are grouped here as two blocks of eight (common for dates or IDs). Adjust grouping if your specification names different field widths.",
  "Sua primeira linha começa com dezesseis dígitos consecutivos. Eles foram agrupados aqui em dois blocos de oito (comum para datas ou IDs). Ajuste o agrupamento se sua especificação define larguras de campo diferentes.",
  "Su primera línea empieza con dieciséis dígitos consecutivos. Aquí se agrupan en dos bloques de ocho (habitual en fechas o ID). Ajuste la agrupación si su especificación indica otros anchos de campo.",
  "Votre première ligne commence par seize chiffres consécutifs. Ils sont regroupés ici en deux blocs de huit (courant pour les dates ou identifiants). Ajustez le regroupement si votre spécification indique d'autres largeurs de champ.",
  "Ihre erste Zeile beginnt mit sechzehn aufeinanderfolgenden Ziffern. Sie sind hier in zwei Achterblöcke gruppiert (üblich für Datumsangaben oder IDs). Passen Sie die Gruppierung an, wenn Ihre Spezifikation andere Feldbreiten vorgibt.",
  "La tua prima riga inizia con sedici cifre consecutive. Qui sono raggruppate in due blocchi da otto (comune per date o ID). Adatta il raggruppamento se la tua specifica indica larghezze di campo diverse.",
  "Twój pierwszy wiersz zaczyna się od szesnastu kolejnych cyfr. Są tu pogrupowane w dwa bloki po osiem (typowe dla dat lub identyfikatorów). Dostosuj grupowanie, jeśli specyfikacja podaje inne szerokości pól.",
  "Prima linie începe cu șaisprezece cifre consecutive. Aici sunt grupate în două blocuri de câte opt (obișnuit pentru date sau ID-uri). Ajustați gruparea dacă specificația indică alte lățimi de câmp.",
  "Az első sor tizenhat egymást követő számjeggyel kezdődik. Itt két nyolcas blokkba vannak csoportosítva (dátumoknál vagy azonosítóknál gyakori). Igazítsa a csoportosítást, ha a specifikáció más mezőszélességet ír elő.",
  "Váš první řádek začíná šestnácti po sobě jdoucími číslicemi. Zde jsou seskupeny do dvou bloků po osmi (běžné u dat nebo ID). Pokud specifikace uvádí jiné šířky polí, seskupení upravte.",
  "1 行目は 16 桁の連続した数字で始まります。ここでは 8 桁ずつ 2 つのブロックにまとめています（日付や ID でよく見られます）。仕様でフィールド幅が異なる場合はグループ化を調整してください。",
  "您的第一行以十六个连续数字开头。这里将其分为两组各八位（常见于日期或 ID）。如果规格说明定义了不同的字段宽度，请调整分组。",
  "您的第一行以十六個連續數字開頭。這裡將其分為兩組各八位（常見於日期或 ID）。若規格說明定義了不同的欄位寬度，請調整分組。")
A("[ReplaceAll] Segmented output missing.", "[ReplaceAll] Saída segmentada ausente.", "[ReplaceAll] Falta la salida segmentada.", "[ReplaceAll] Sortie segmentée manquante.", "[ReplaceAll] Segmentierte Ausgabe fehlt.", "[ReplaceAll] Output segmentato mancante.", "[ReplaceAll] Brak wyjścia segmentowego.", "[ReplaceAll] Lipsește ieșirea segmentată.", "[ReplaceAll] Hiányzik a szegmentált kimenet.", "[ReplaceAll] Chybí segmentovaný výstup.", "[ReplaceAll] セグメント出力がありません。", "[ReplaceAll] 缺少分段输出。", "[ReplaceAll] 缺少分段輸出。")
A("[ReplaceAll] Segmented part failed.", "[ReplaceAll] Falha em uma parte segmentada.", "[ReplaceAll] Falló una parte segmentada.", "[ReplaceAll] Échec d'une partie segmentée.", "[ReplaceAll] Segmentierter Teil fehlgeschlagen.", "[ReplaceAll] Parte segmentata non riuscita.", "[ReplaceAll] Część segmentowa nie powiodła się.", "[ReplaceAll] O parte segmentată a eșuat.", "[ReplaceAll] Egy szegmentált rész sikertelen.", "[ReplaceAll] Segmentovaná část selhala.", "[ReplaceAll] セグメントの処理に失敗しました。", "[ReplaceAll] 分段部分失败。", "[ReplaceAll] 分段部分失敗。")
A("[Scan] Based on the first %d non-empty lines (maximum %d). Detected delimiter [%s], fields: %d.",
  "[Varredura] Com base nas primeiras %d linhas não vazias (máximo %d). Delimitador detectado [%s], campos: %d.",
  "[Análisis] Basado en las primeras %d líneas no vacías (máximo %d). Delimitador detectado [%s], campos: %d.",
  "[Analyse] Basée sur les %d premières lignes non vides (maximum %d). Délimiteur détecté [%s], champs : %d.",
  "[Scan] Basierend auf den ersten %d nicht leeren Zeilen (maximal %d). Erkanntes Trennzeichen [%s], Felder: %d.",
  "[Scansione] Basata sulle prime %d righe non vuote (massimo %d). Delimitatore rilevato [%s], campi: %d.",
  "[Skan] Na podstawie pierwszych %d niepustych wierszy (maksymalnie %d). Wykryty separator [%s], pola: %d.",
  "[Scanare] Pe baza primelor %d linii nevide (maximum %d). Delimitator detectat [%s], câmpuri: %d.",
  "[Vizsgálat] Az első %d nem üres sor alapján (legfeljebb %d). Észlelt elválasztó [%s], mezők: %d.",
  "[Sken] Na základě prvních %d neprázdných řádků (maximálně %d). Zjištěný oddělovač [%s], pole: %d.",
  "[スキャン] 空でない最初の %d 行に基づく（最大 %d）。検出した区切り文字 [%s]、フィールド数: %d。",
  "[扫描] 基于前 %d 个非空行（最多 %d）。检测到的分隔符 [%s]，字段数：%d。",
  "[掃描] 依據前 %d 個非空行（最多 %d）。偵測到的分隔符號 [%s]，欄位數：%d。")
A("[Scan] Based on the first %d non-empty lines read from this file (maximum %d). Layout: fixed-width / positional (few delimiter characters on line 1).",
  "[Varredura] Com base nas primeiras %d linhas não vazias lidas deste arquivo (máximo %d). Layout: largura fixa / posicional (poucos delimitadores na linha 1).",
  "[Análisis] Basado en las primeras %d líneas no vacías leídas de este archivo (máximo %d). Diseño: ancho fijo / posicional (pocos delimitadores en la línea 1).",
  "[Analyse] Basée sur les %d premières lignes non vides lues dans ce fichier (maximum %d). Format : largeur fixe / positionnel (peu de délimiteurs sur la ligne 1).",
  "[Scan] Basierend auf den ersten %d nicht leeren Zeilen dieser Datei (maximal %d). Layout: feste Breite / positionell (wenige Trennzeichen in Zeile 1).",
  "[Scansione] Basata sulle prime %d righe non vuote lette da questo file (massimo %d). Layout: larghezza fissa / posizionale (pochi delimitatori nella riga 1).",
  "[Skan] Na podstawie pierwszych %d niepustych wierszy z tego pliku (maksymalnie %d). Układ: stała szerokość / pozycyjny (mało separatorów w wierszu 1).",
  "[Scanare] Pe baza primelor %d linii nevide citite din acest fișier (maximum %d). Format: lățime fixă / pozițional (puțini delimitatori pe linia 1).",
  "[Vizsgálat] A fájlból beolvasott első %d nem üres sor alapján (legfeljebb %d). Elrendezés: fix szélességű / pozicionális (kevés elválasztó az 1. sorban).",
  "[Sken] Na základě prvních %d neprázdných řádků z tohoto souboru (maximálně %d). Rozvržení: pevná šířka / poziční (málo oddělovačů na řádku 1).",
  "[スキャン] このファイルから読み込んだ空でない最初の %d 行に基づく（最大 %d）。レイアウト: 固定長 / 位置指定（1 行目に区切り文字がほとんどない）。",
  "[扫描] 基于从此文件读取的前 %d 个非空行（最多 %d）。布局：固定宽度 / 定位式（第 1 行分隔符很少）。",
  "[掃描] 依據從此檔案讀取的前 %d 個非空行（最多 %d）。版面：固定寬度 / 定位式（第 1 行分隔符號很少）。")
A("filter", "filtro", "filtro", "filtre", "Filter", "filtro", "filtr", "filtru", "szűrés", "filtr", "フィルター", "过滤", "篩選")
A("match", "correspondência", "coincidencia", "correspondance", "Treffer", "corrispondenza", "dopasowanie", "potrivire", "egyezés", "shoda", "一致", "匹配", "比對")
A("more technical info ...", "mais informações técnicas ...", "más información técnica ...", "plus d'informations techniques ...", "weitere technische Infos ...", "altre informazioni tecniche ...", "więcej informacji technicznych ...", "mai multe informații tehnice ...", "további műszaki információ ...", "další technické informace ...", "技術情報の詳細 ...", "更多技术信息 ...", "更多技術資訊 ...")
A("regex", "regex", "regex", "regex", "Regex", "regex", "regex", "regex", "regex", "regex", "正規表現", "正则", "正則")
A("replace", "substituição", "reemplazo", "remplacement", "Ersetzen", "sostituzione", "zamiana", "înlocuire", "csere", "nahrazení", "置換", "替换", "取代")
A("resp: ", "resp.: ", "resp.: ", "rép. : ", "Antw.: ", "risp.: ", "odp.: ", "răsp.: ", "válasz: ", "odp.: ", "応答: ", "响应：", "回應：")
A("saved", "salvo", "guardado", "enregistré", "gespeichert", "salvato", "zapisano", "salvat", "mentve", "uloženo", "保存済み", "已保存", "已儲存")
